
package de.integrationsservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 */
@WebService(name = "Integration", targetNamespace = "http://www.gillardon.de/marzipan/webservices/integrationsservice/wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Integration {


    /**
     * @return returns de.gillardon.marzipan.integrationsservice.ServiceVersionResponse
     */
    @WebMethod(action = "urn:getServiceVersion")
    @WebResult(name = "ServiceVersionResponse", partName = "ServiceVersionResponse")
    public ServiceVersionResponse getServiceVersion();

    /**
     * @param exportAnfrage
     * @return returns de.gillardon.marzipan.integrationsservice.Export
     */
    @WebMethod(action = "urn:export")
    @WebResult(name = "Export", partName = "Export")
    public Export export(
            @WebParam(name = "ExportAnfrage", partName = "ExportAnfrage")
            ExportAnfrage exportAnfrage);

    /**
     * @param statusuebergang
     * @return returns de.gillardon.marzipan.integrationsservice.Ergebnis
     */
    @WebMethod(action = "urn:statusuebergangGeschaeft")
    @WebResult(name = "Ergebnis", partName = "Ergebnis")
    public Ergebnis statusuebergangGeschaeft(
            @WebParam(name = "Statusuebergang", partName = "Statusuebergang")
            Statusuebergang statusuebergang);

    /**
     * @param rekonditionierung
     * @return returns de.gillardon.marzipan.integrationsservice.Ergebnis
     */
    @WebMethod(action = "urn:rekonditionierungKreditgeschaeft")
    @WebResult(name = "Ergebnis", partName = "Ergebnis")
    public Ergebnis rekonditionierungKreditgeschaeft(
            @WebParam(name = "Rekonditionierung", partName = "Rekonditionierung")
            Rekonditionierung rekonditionierung);

    /**
     * @param autoImport
     * @return returns de.gillardon.marzipan.integrationsservice.Ergebnis
     */
    @WebMethod(action = "urn:autoImportKreditgeschaeft")
    @WebResult(name = "Ergebnis", partName = "Ergebnis")
    public Ergebnis autoImportKreditgeschaeft(
            @WebParam(name = "AutoImport", partName = "AutoImport")
            AutoImport autoImport);

    /**
     * @param autoUpdate
     * @return returns de.gillardon.marzipan.integrationsservice.Ergebnis
     */
    @WebMethod(action = "urn:autoUpdateKreditgeschaeft")
    @WebResult(name = "Ergebnis", partName = "Ergebnis")
    public Ergebnis autoUpdateKreditgeschaeft(
            @WebParam(name = "AutoUpdate", partName = "AutoUpdate")
            AutoUpdate autoUpdate);

    /**
     * @param autoUpdateKopfdaten
     * @return returns de.gillardon.marzipan.integrationsservice.AutoUpdateKopfdatenResponse
     */
    @WebMethod(action = "urn:autoUpdateKopfdaten")
    @WebResult(name = "AutoUpdateKopfdatenResponse", partName = "AutoUpdateKopfdatenResponse")
    public AutoUpdateKopfdatenResponse autoUpdateKopfdaten(
            @WebParam(name = "AutoUpdateKopfdaten", partName = "AutoUpdateKopfdaten")
            AutoUpdateKopfdaten autoUpdateKopfdaten);

    /**
     * @param importMitMelden
     * @return returns de.gillardon.marzipan.integrationsservice.Ergebnis
     */
    @WebMethod(action = "urn:autoImportMitMeldenGeschaeft")
    @WebResult(name = "Ergebnis", partName = "Ergebnis")
    public Ergebnis autoImportMitMeldenGeschaeft(
            @WebParam(name = "ImportMitMelden", partName = "ImportMitMelden")
            ImportMitMelden importMitMelden);

    /**
     * @param aktualitaetZinsstrukturListe
     */
    @WebMethod(action = "urn:pruefeAktualitaetZinsstrukturen")
    public void pruefeAktualitaetZinsstrukturen(
            @WebParam(name = "AktualitaetZinsstrukturListe", mode = WebParam.Mode.INOUT, partName = "AktualitaetZinsstrukturListe")
            Holder<AktualitaetZinsstrukturListe> aktualitaetZinsstrukturListe);

}
