
package de.integrationsservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 */
@WebService(name = "ExternMeldenService", targetNamespace = "http://www.gillardon.de/marzipan/integrationsservice/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ExternMeldenService {


    /**
     * @param parameters
     * @return returns de.gillardon.marzipan.integrationsservice.Ergebnis
     */
    @WebMethod(action = "urn:melden")
    @WebResult(name = "Ergebnis", targetNamespace = "http://www.gillardon.de/marzipan/integrationsservice", partName = "parameters")
    public Ergebnis melden(
            @WebParam(name = "Geschaefte", targetNamespace = "http://www.gillardon.de/marzipan/integrationsservice", partName = "parameters")
            Geschaefte parameters);

}
