/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Der Abgrenzungsplan für das Disagio und Gebühren in monatlichem Raster.
 */
@JsonPropertyOrder({
        Abgrenzung.JSON_PROPERTY_ZEILEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Abgrenzung {
    public static final String JSON_PROPERTY_ZEILEN = "zeilen";
    private List<@Valid AbgrenzungZeile> zeilen;

    public Abgrenzung() {
    }

    public Abgrenzung zeilen(List<@Valid AbgrenzungZeile> zeilen) {

        this.zeilen = zeilen;
        return this;
    }

    public Abgrenzung addZeilenItem(AbgrenzungZeile zeilenItem) {
        if (this.zeilen == null) {
            this.zeilen = new ArrayList<>();
        }
        this.zeilen.add(zeilenItem);
        return this;
    }

    /**
     * Im Abgrenzungsplan werden Zinsen, Gebühren und Disagio am Monatsultimo abgegrenzt. Zusätzlich wird die monatliche mittlere Restschuld, das unverbrauchte Disagio und das Restkapital ausgewiesen.
     *
     * @return zeilen
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZEILEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid AbgrenzungZeile> getZeilen() {
        return zeilen;
    }


    @JsonProperty(JSON_PROPERTY_ZEILEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZeilen(List<@Valid AbgrenzungZeile> zeilen) {
        this.zeilen = zeilen;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Abgrenzung abgrenzung = (Abgrenzung) o;
        return Objects.equals(this.zeilen, abgrenzung.zeilen);
    }

    @Override
    public int hashCode() {
        return Objects.hash(zeilen);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Abgrenzung {\n");
        sb.append("    zeilen: ").append(toIndentedString(zeilen)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

