/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.Objects;

/**
 * AdressrisikoExterneSicherheiten
 */
@JsonPropertyOrder({
        AdressrisikoExterneSicherheiten.JSON_PROPERTY_LGD_GENERATOR,
        AdressrisikoExterneSicherheiten.JSON_PROPERTY_RISIKODATEN,
        AdressrisikoExterneSicherheiten.JSON_PROPERTY_EKKDATEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class AdressrisikoExterneSicherheiten {
    public static final String JSON_PROPERTY_LGD_GENERATOR = "lgdGenerator";
    private LGDGenerator lgdGenerator;

    public static final String JSON_PROPERTY_RISIKODATEN = "risikodaten";
    private Risikodaten risikodaten;

    public static final String JSON_PROPERTY_EKKDATEN = "ekkdaten";
    private Ekkdaten ekkdaten;

    public AdressrisikoExterneSicherheiten() {
    }

    public AdressrisikoExterneSicherheiten lgdGenerator(LGDGenerator lgdGenerator) {

        this.lgdGenerator = lgdGenerator;
        return this;
    }

    /**
     * Get lgdGenerator
     *
     * @return lgdGenerator
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_LGD_GENERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LGDGenerator getLgdGenerator() {
        return lgdGenerator;
    }


    @JsonProperty(JSON_PROPERTY_LGD_GENERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLgdGenerator(LGDGenerator lgdGenerator) {
        this.lgdGenerator = lgdGenerator;
    }

    public AdressrisikoExterneSicherheiten risikodaten(Risikodaten risikodaten) {

        this.risikodaten = risikodaten;
        return this;
    }

    /**
     * Get risikodaten
     *
     * @return risikodaten
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RISIKODATEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Risikodaten getRisikodaten() {
        return risikodaten;
    }


    @JsonProperty(JSON_PROPERTY_RISIKODATEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRisikodaten(Risikodaten risikodaten) {
        this.risikodaten = risikodaten;
    }

    public AdressrisikoExterneSicherheiten ekkdaten(Ekkdaten ekkdaten) {

        this.ekkdaten = ekkdaten;
        return this;
    }

    /**
     * Get ekkdaten
     *
     * @return ekkdaten
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_EKKDATEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Ekkdaten getEkkdaten() {
        return ekkdaten;
    }


    @JsonProperty(JSON_PROPERTY_EKKDATEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEkkdaten(Ekkdaten ekkdaten) {
        this.ekkdaten = ekkdaten;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdressrisikoExterneSicherheiten adressrisikoExterneSicherheiten = (AdressrisikoExterneSicherheiten) o;
        return Objects.equals(this.lgdGenerator, adressrisikoExterneSicherheiten.lgdGenerator) &&
                Objects.equals(this.risikodaten, adressrisikoExterneSicherheiten.risikodaten) &&
                Objects.equals(this.ekkdaten, adressrisikoExterneSicherheiten.ekkdaten);
    }

    @Override
    public int hashCode() {
        return Objects.hash(lgdGenerator, risikodaten, ekkdaten);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AdressrisikoExterneSicherheiten {\n");
        sb.append("    lgdGenerator: ").append(toIndentedString(lgdGenerator)).append("\n");
        sb.append("    risikodaten: ").append(toIndentedString(risikodaten)).append("\n");
        sb.append("    ekkdaten: ").append(toIndentedString(ekkdaten)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

