/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gibt den Statusübergang an, welcher durchgeführt werden soll.
 */
public enum Aktion {

    MELDEN("MELDEN"),

    FREIGEBEN("FREIGEBEN"),

    SPERREN("SPERREN"),

    ANFRAGEN_TREASURY("ANFRAGEN_TREASURY"),

    ANFRAGEN_FACHLICH("ANFRAGEN_FACHLICH"),

    PRUEFEN_TREASURY("PRUEFEN_TREASURY"),

    PRUEFEN_FACHLICH("PRUEFEN_FACHLICH"),

    RUECKSETZEN("RUECKSETZEN");

    private String value;

    Aktion(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static Aktion fromValue(String value) {
        for (Aktion b : Aktion.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

