/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Zahlungen werden entweder gleich, oder erst zum Periodenende auf den Saldo angerechnet.
 */
public enum AnrechnungsModus {

    MIT_JEDER_RATE("MIT_JEDER_RATE"),

    ZUM_PERIODENENDE("ZUM_PERIODENENDE");

    private String value;

    AnrechnungsModus(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static AnrechnungsModus fromValue(String value) {
        for (AnrechnungsModus b : AnrechnungsModus.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

