/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * ImportResponse
 */
@JsonPropertyOrder({
        ImportResponse.JSON_PROPERTY_VORGANG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class ImportResponse {
    public static final String JSON_PROPERTY_VORGANG = "vorgang";
    private String vorgang;

    public ImportResponse() {
    }

    public ImportResponse vorgang(String vorgang) {

        this.vorgang = vorgang;
        return this;
    }

    /**
     * Get vorgang
     *
     * @return vorgang
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_VORGANG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getVorgang() {
        return vorgang;
    }


    @JsonProperty(JSON_PROPERTY_VORGANG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVorgang(String vorgang) {
        this.vorgang = vorgang;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ImportResponse importResponse = (ImportResponse) o;
        return Objects.equals(this.vorgang, importResponse.vorgang);
    }

    @Override
    public int hashCode() {
        return Objects.hash(vorgang);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ImportResponse {\n");
        sb.append("    vorgang: ").append(toIndentedString(vorgang)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

