/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * MarktdatenPricingkriterien
 */
@JsonPropertyOrder({
        MarktdatenPricingkriterien.JSON_PROPERTY_NAME,
        MarktdatenPricingkriterien.JSON_PROPERTY_AUSWAHL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class MarktdatenPricingkriterien {
    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_AUSWAHL = "auswahl";
    private String auswahl;

    public MarktdatenPricingkriterien() {
    }

    public MarktdatenPricingkriterien name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Der technische Name des Pricingkriteriums.
     *
     * @return name
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }


    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(String name) {
        this.name = name;
    }

    public MarktdatenPricingkriterien auswahl(String auswahl) {

        this.auswahl = auswahl;
        return this;
    }

    /**
     * Der ausgewählte Wert des Pricingkriteriums.
     *
     * @return auswahl
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_AUSWAHL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAuswahl() {
        return auswahl;
    }


    @JsonProperty(JSON_PROPERTY_AUSWAHL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAuswahl(String auswahl) {
        this.auswahl = auswahl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MarktdatenPricingkriterien marktdatenPricingkriterien = (MarktdatenPricingkriterien) o;
        return Objects.equals(this.name, marktdatenPricingkriterien.name) &&
                Objects.equals(this.auswahl, marktdatenPricingkriterien.auswahl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, auswahl);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MarktdatenPricingkriterien {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    auswahl: ").append(toIndentedString(auswahl)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

