/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Quickcheckdaten für LGD Generator
 */
@JsonPropertyOrder({
        Quickcheckdaten.JSON_PROPERTY_SICHERHEITENCODE,
        Quickcheckdaten.JSON_PROPERTY_BELEIHUNGSWERT,
        Quickcheckdaten.JSON_PROPERTY_GRUNDSCHULD_R1_GESAMT,
        Quickcheckdaten.JSON_PROPERTY_GRUNDSCHULD_R1,
        Quickcheckdaten.JSON_PROPERTY_GRUNDSCHULD_R2_GESAMT,
        Quickcheckdaten.JSON_PROPERTY_GRUNDSCHULD_R2,
        Quickcheckdaten.JSON_PROPERTY_ZUSATZSICHERHEIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Quickcheckdaten {
    public static final String JSON_PROPERTY_SICHERHEITENCODE = "sicherheitencode";
    private String sicherheitencode;

    public static final String JSON_PROPERTY_BELEIHUNGSWERT = "beleihungswert";
    private BigDecimal beleihungswert;

    public static final String JSON_PROPERTY_GRUNDSCHULD_R1_GESAMT = "grundschuldR1Gesamt";
    private BigDecimal grundschuldR1Gesamt;

    public static final String JSON_PROPERTY_GRUNDSCHULD_R1 = "grundschuldR1";
    private BigDecimal grundschuldR1;

    public static final String JSON_PROPERTY_GRUNDSCHULD_R2_GESAMT = "grundschuldR2Gesamt";
    private BigDecimal grundschuldR2Gesamt;

    public static final String JSON_PROPERTY_GRUNDSCHULD_R2 = "grundschuldR2";
    private BigDecimal grundschuldR2;

    public static final String JSON_PROPERTY_ZUSATZSICHERHEIT = "zusatzsicherheit";
    private BigDecimal zusatzsicherheit;

    public Quickcheckdaten() {
    }

    public Quickcheckdaten sicherheitencode(String sicherheitencode) {

        this.sicherheitencode = sicherheitencode;
        return this;
    }

    /**
     * Sicherheitencode
     *
     * @return sicherheitencode
     */
    @jakarta.annotation.Nonnull
    @NotNull

    @JsonProperty(JSON_PROPERTY_SICHERHEITENCODE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getSicherheitencode() {
        return sicherheitencode;
    }


    @JsonProperty(JSON_PROPERTY_SICHERHEITENCODE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSicherheitencode(String sicherheitencode) {
        this.sicherheitencode = sicherheitencode;
    }

    public Quickcheckdaten beleihungswert(BigDecimal beleihungswert) {

        this.beleihungswert = beleihungswert;
        return this;
    }

    /**
     * Beleihungswert (Kreditrisiko).
     *
     * @return beleihungswert
     */
    @jakarta.annotation.Nonnull
    @NotNull
    @Valid

    @JsonProperty(JSON_PROPERTY_BELEIHUNGSWERT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public BigDecimal getBeleihungswert() {
        return beleihungswert;
    }


    @JsonProperty(JSON_PROPERTY_BELEIHUNGSWERT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBeleihungswert(BigDecimal beleihungswert) {
        this.beleihungswert = beleihungswert;
    }

    public Quickcheckdaten grundschuldR1Gesamt(BigDecimal grundschuldR1Gesamt) {

        this.grundschuldR1Gesamt = grundschuldR1Gesamt;
        return this;
    }

    /**
     * Grundschuld Rang1 Gesamt.
     *
     * @return grundschuldR1Gesamt
     */
    @jakarta.annotation.Nonnull
    @NotNull
    @Valid

    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R1_GESAMT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public BigDecimal getGrundschuldR1Gesamt() {
        return grundschuldR1Gesamt;
    }


    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R1_GESAMT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setGrundschuldR1Gesamt(BigDecimal grundschuldR1Gesamt) {
        this.grundschuldR1Gesamt = grundschuldR1Gesamt;
    }

    public Quickcheckdaten grundschuldR1(BigDecimal grundschuldR1) {

        this.grundschuldR1 = grundschuldR1;
        return this;
    }

    /**
     * Grundschuld Rang1 Externe Sicherheiten.
     *
     * @return grundschuldR1
     */
    @jakarta.annotation.Nonnull
    @NotNull
    @Valid

    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R1)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public BigDecimal getGrundschuldR1() {
        return grundschuldR1;
    }


    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R1)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setGrundschuldR1(BigDecimal grundschuldR1) {
        this.grundschuldR1 = grundschuldR1;
    }

    public Quickcheckdaten grundschuldR2Gesamt(BigDecimal grundschuldR2Gesamt) {

        this.grundschuldR2Gesamt = grundschuldR2Gesamt;
        return this;
    }

    /**
     * Grundschuld Rang2 Gesamt.
     *
     * @return grundschuldR2Gesamt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R2_GESAMT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getGrundschuldR2Gesamt() {
        return grundschuldR2Gesamt;
    }


    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R2_GESAMT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGrundschuldR2Gesamt(BigDecimal grundschuldR2Gesamt) {
        this.grundschuldR2Gesamt = grundschuldR2Gesamt;
    }

    public Quickcheckdaten grundschuldR2(BigDecimal grundschuldR2) {

        this.grundschuldR2 = grundschuldR2;
        return this;
    }

    /**
     * Grundschuld Rang2 Externe Sicherheiten.
     *
     * @return grundschuldR2
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R2)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getGrundschuldR2() {
        return grundschuldR2;
    }


    @JsonProperty(JSON_PROPERTY_GRUNDSCHULD_R2)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGrundschuldR2(BigDecimal grundschuldR2) {
        this.grundschuldR2 = grundschuldR2;
    }

    public Quickcheckdaten zusatzsicherheit(BigDecimal zusatzsicherheit) {

        this.zusatzsicherheit = zusatzsicherheit;
        return this;
    }

    /**
     * Zusatzsicherheit.
     *
     * @return zusatzsicherheit
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZUSATZSICHERHEIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getZusatzsicherheit() {
        return zusatzsicherheit;
    }


    @JsonProperty(JSON_PROPERTY_ZUSATZSICHERHEIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZusatzsicherheit(BigDecimal zusatzsicherheit) {
        this.zusatzsicherheit = zusatzsicherheit;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Quickcheckdaten quickcheckdaten = (Quickcheckdaten) o;
        return Objects.equals(this.sicherheitencode, quickcheckdaten.sicherheitencode) &&
                Objects.equals(this.beleihungswert, quickcheckdaten.beleihungswert) &&
                Objects.equals(this.grundschuldR1Gesamt, quickcheckdaten.grundschuldR1Gesamt) &&
                Objects.equals(this.grundschuldR1, quickcheckdaten.grundschuldR1) &&
                Objects.equals(this.grundschuldR2Gesamt, quickcheckdaten.grundschuldR2Gesamt) &&
                Objects.equals(this.grundschuldR2, quickcheckdaten.grundschuldR2) &&
                Objects.equals(this.zusatzsicherheit, quickcheckdaten.zusatzsicherheit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sicherheitencode, beleihungswert, grundschuldR1Gesamt, grundschuldR1, grundschuldR2Gesamt, grundschuldR2, zusatzsicherheit);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Quickcheckdaten {\n");
        sb.append("    sicherheitencode: ").append(toIndentedString(sicherheitencode)).append("\n");
        sb.append("    beleihungswert: ").append(toIndentedString(beleihungswert)).append("\n");
        sb.append("    grundschuldR1Gesamt: ").append(toIndentedString(grundschuldR1Gesamt)).append("\n");
        sb.append("    grundschuldR1: ").append(toIndentedString(grundschuldR1)).append("\n");
        sb.append("    grundschuldR2Gesamt: ").append(toIndentedString(grundschuldR2Gesamt)).append("\n");
        sb.append("    grundschuldR2: ").append(toIndentedString(grundschuldR2)).append("\n");
        sb.append("    zusatzsicherheit: ").append(toIndentedString(zusatzsicherheit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

