/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.Objects;

/**
 * Sondervereinbarungen des Rollovers.
 */
@JsonPropertyOrder({
        SondervereinbarungenRollover.JSON_PROPERTY_SONDERTILGUNGEN,
        SondervereinbarungenRollover.JSON_PROPERTY_STUECKZINS,
        SondervereinbarungenRollover.JSON_PROPERTY_TEILVALUTIERUNGEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class SondervereinbarungenRollover {
    public static final String JSON_PROPERTY_SONDERTILGUNGEN = "sondertilgungen";
    private Sondertilgungen sondertilgungen;

    public static final String JSON_PROPERTY_STUECKZINS = "stueckzins";
    private Stueckzins stueckzins;

    public static final String JSON_PROPERTY_TEILVALUTIERUNGEN = "teilvalutierungen";
    private Teilvalutierungen teilvalutierungen;

    public SondervereinbarungenRollover() {
    }

    public SondervereinbarungenRollover sondertilgungen(Sondertilgungen sondertilgungen) {

        this.sondertilgungen = sondertilgungen;
        return this;
    }

    /**
     * Get sondertilgungen
     *
     * @return sondertilgungen
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SONDERTILGUNGEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Sondertilgungen getSondertilgungen() {
        return sondertilgungen;
    }


    @JsonProperty(JSON_PROPERTY_SONDERTILGUNGEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSondertilgungen(Sondertilgungen sondertilgungen) {
        this.sondertilgungen = sondertilgungen;
    }

    public SondervereinbarungenRollover stueckzins(Stueckzins stueckzins) {

        this.stueckzins = stueckzins;
        return this;
    }

    /**
     * Get stueckzins
     *
     * @return stueckzins
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_STUECKZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Stueckzins getStueckzins() {
        return stueckzins;
    }


    @JsonProperty(JSON_PROPERTY_STUECKZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStueckzins(Stueckzins stueckzins) {
        this.stueckzins = stueckzins;
    }

    public SondervereinbarungenRollover teilvalutierungen(Teilvalutierungen teilvalutierungen) {

        this.teilvalutierungen = teilvalutierungen;
        return this;
    }

    /**
     * Get teilvalutierungen
     *
     * @return teilvalutierungen
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_TEILVALUTIERUNGEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Teilvalutierungen getTeilvalutierungen() {
        return teilvalutierungen;
    }


    @JsonProperty(JSON_PROPERTY_TEILVALUTIERUNGEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTeilvalutierungen(Teilvalutierungen teilvalutierungen) {
        this.teilvalutierungen = teilvalutierungen;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SondervereinbarungenRollover sondervereinbarungenRollover = (SondervereinbarungenRollover) o;
        return Objects.equals(this.sondertilgungen, sondervereinbarungenRollover.sondertilgungen) &&
                Objects.equals(this.stueckzins, sondervereinbarungenRollover.stueckzins) &&
                Objects.equals(this.teilvalutierungen, sondervereinbarungenRollover.teilvalutierungen);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sondertilgungen, stueckzins, teilvalutierungen);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SondervereinbarungenRollover {\n");
        sb.append("    sondertilgungen: ").append(toIndentedString(sondertilgungen)).append("\n");
        sb.append("    stueckzins: ").append(toIndentedString(stueckzins)).append("\n");
        sb.append("    teilvalutierungen: ").append(toIndentedString(teilvalutierungen)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

