/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Hier können Teilvalutierungen erfasst werden.
 */
@JsonPropertyOrder({
        Teilvalutierungen.JSON_PROPERTY_RATENANPASSUNG,
        Teilvalutierungen.JSON_PROPERTY_TEILVALUTIERUNGEN,
        Teilvalutierungen.JSON_PROPERTY_AKTIV
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Teilvalutierungen {
    public static final String JSON_PROPERTY_RATENANPASSUNG = "ratenanpassung";
    private Boolean ratenanpassung;

    public static final String JSON_PROPERTY_TEILVALUTIERUNGEN = "teilvalutierungen";
    private List<@Valid Teilvalutierung> teilvalutierungen;

    public static final String JSON_PROPERTY_AKTIV = "aktiv";
    private Boolean aktiv;

    public Teilvalutierungen() {
    }

    public Teilvalutierungen ratenanpassung(Boolean ratenanpassung) {

        this.ratenanpassung = ratenanpassung;
        return this;
    }

    /**
     * Nach jeder Auszahlung wird die Rate soweit erhöht, dass sich am relativen Tilgungsverlauf nichts ändert. Diese Einstellung ist nur für Annuitätendarlehen relevant.
     *
     * @return ratenanpassung
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_RATENANPASSUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRatenanpassung() {
        return ratenanpassung;
    }


    @JsonProperty(JSON_PROPERTY_RATENANPASSUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRatenanpassung(Boolean ratenanpassung) {
        this.ratenanpassung = ratenanpassung;
    }

    public Teilvalutierungen teilvalutierungen(List<@Valid Teilvalutierung> teilvalutierungen) {

        this.teilvalutierungen = teilvalutierungen;
        return this;
    }

    public Teilvalutierungen addTeilvalutierungenItem(Teilvalutierung teilvalutierungenItem) {
        if (this.teilvalutierungen == null) {
            this.teilvalutierungen = new ArrayList<>();
        }
        this.teilvalutierungen.add(teilvalutierungenItem);
        return this;
    }

    /**
     * Tabelle der Teilvalutierungen
     *
     * @return teilvalutierungen
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_TEILVALUTIERUNGEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid Teilvalutierung> getTeilvalutierungen() {
        return teilvalutierungen;
    }


    @JsonProperty(JSON_PROPERTY_TEILVALUTIERUNGEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTeilvalutierungen(List<@Valid Teilvalutierung> teilvalutierungen) {
        this.teilvalutierungen = teilvalutierungen;
    }

    public Teilvalutierungen aktiv(Boolean aktiv) {

        this.aktiv = aktiv;
        return this;
    }

    /**
     * Get aktiv
     *
     * @return aktiv
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_AKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAktiv() {
        return aktiv;
    }


    @JsonProperty(JSON_PROPERTY_AKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAktiv(Boolean aktiv) {
        this.aktiv = aktiv;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Teilvalutierungen teilvalutierungen = (Teilvalutierungen) o;
        return Objects.equals(this.ratenanpassung, teilvalutierungen.ratenanpassung) &&
                Objects.equals(this.teilvalutierungen, teilvalutierungen.teilvalutierungen) &&
                Objects.equals(this.aktiv, teilvalutierungen.aktiv);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ratenanpassung, teilvalutierungen, aktiv);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Teilvalutierungen {\n");
        sb.append("    ratenanpassung: ").append(toIndentedString(ratenanpassung)).append("\n");
        sb.append("    teilvalutierungen: ").append(toIndentedString(teilvalutierungen)).append("\n");
        sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

