/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * Im Tilgungsplan wird der Tilgungsverlauf des Darlehens dargestellt.
 */
@JsonPropertyOrder({
        TilgungsplanZeile.JSON_PROPERTY_AKTUELLER_ZINS,
        TilgungsplanZeile.JSON_PROPERTY_BEWEGUNG,
        TilgungsplanZeile.JSON_PROPERTY_ART,
        TilgungsplanZeile.JSON_PROPERTY_RESTKAPITAL,
        TilgungsplanZeile.JSON_PROPERTY_TILGUNG,
        TilgungsplanZeile.JSON_PROPERTY_VALUTA,
        TilgungsplanZeile.JSON_PROPERTY_ZINS,
        TilgungsplanZeile.JSON_PROPERTY_ZINSSALDO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class TilgungsplanZeile {
    public static final String JSON_PROPERTY_AKTUELLER_ZINS = "aktuellerZins";
    private BigDecimal aktuellerZins;

    public static final String JSON_PROPERTY_BEWEGUNG = "bewegung";
    private BigDecimal bewegung;

    public static final String JSON_PROPERTY_ART = "art";
    private TilgungsplanArt art;

    public static final String JSON_PROPERTY_RESTKAPITAL = "restkapital";
    private BigDecimal restkapital;

    public static final String JSON_PROPERTY_TILGUNG = "tilgung";
    private BigDecimal tilgung;

    public static final String JSON_PROPERTY_VALUTA = "valuta";
    private LocalDate valuta;

    public static final String JSON_PROPERTY_ZINS = "zins";
    private BigDecimal zins;

    public static final String JSON_PROPERTY_ZINSSALDO = "zinssaldo";
    private BigDecimal zinssaldo;

    public TilgungsplanZeile() {
    }

    public TilgungsplanZeile aktuellerZins(BigDecimal aktuellerZins) {

        this.aktuellerZins = aktuellerZins;
        return this;
    }

    /**
     * Der ab dem Datum gültige Nominalzinssatz.
     *
     * @return aktuellerZins
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_AKTUELLER_ZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getAktuellerZins() {
        return aktuellerZins;
    }


    @JsonProperty(JSON_PROPERTY_AKTUELLER_ZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAktuellerZins(BigDecimal aktuellerZins) {
        this.aktuellerZins = aktuellerZins;
    }

    public TilgungsplanZeile bewegung(BigDecimal bewegung) {

        this.bewegung = bewegung;
        return this;
    }

    /**
     * Die Höhe des Cashflow.
     *
     * @return bewegung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_BEWEGUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getBewegung() {
        return bewegung;
    }


    @JsonProperty(JSON_PROPERTY_BEWEGUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBewegung(BigDecimal bewegung) {
        this.bewegung = bewegung;
    }

    public TilgungsplanZeile art(TilgungsplanArt art) {

        this.art = art;
        return this;
    }

    /**
     * Get art
     *
     * @return art
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ART)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TilgungsplanArt getArt() {
        return art;
    }


    @JsonProperty(JSON_PROPERTY_ART)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArt(TilgungsplanArt art) {
        this.art = art;
    }

    public TilgungsplanZeile restkapital(BigDecimal restkapital) {

        this.restkapital = restkapital;
        return this;
    }

    /**
     * Die Höhe der Restschuld nach dem Ereignis.
     *
     * @return restkapital
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RESTKAPITAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getRestkapital() {
        return restkapital;
    }


    @JsonProperty(JSON_PROPERTY_RESTKAPITAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRestkapital(BigDecimal restkapital) {
        this.restkapital = restkapital;
    }

    public TilgungsplanZeile tilgung(BigDecimal tilgung) {

        this.tilgung = tilgung;
        return this;
    }

    /**
     * Der Tilgungsanteil des Cashflow.
     *
     * @return tilgung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_TILGUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getTilgung() {
        return tilgung;
    }


    @JsonProperty(JSON_PROPERTY_TILGUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTilgung(BigDecimal tilgung) {
        this.tilgung = tilgung;
    }

    public TilgungsplanZeile valuta(LocalDate valuta) {

        this.valuta = valuta;
        return this;
    }

    /**
     * Das Datum des Ereignisses, wie bspw. \&quot;Zins\&quot; oder \&quot;Tilgung\&quot;.
     *
     * @return valuta
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_VALUTA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LocalDate getValuta() {
        return valuta;
    }


    @JsonProperty(JSON_PROPERTY_VALUTA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setValuta(LocalDate valuta) {
        this.valuta = valuta;
    }

    public TilgungsplanZeile zins(BigDecimal zins) {

        this.zins = zins;
        return this;
    }

    /**
     * Der Zinsanteil des Cashflow.
     *
     * @return zins
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getZins() {
        return zins;
    }


    @JsonProperty(JSON_PROPERTY_ZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZins(BigDecimal zins) {
        this.zins = zins;
    }

    public TilgungsplanZeile zinssaldo(BigDecimal zinssaldo) {

        this.zinssaldo = zinssaldo;
        return this;
    }

    /**
     * Die Höhe des Zinssaldos nach dem Ereignis.
     *
     * @return zinssaldo
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSSALDO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getZinssaldo() {
        return zinssaldo;
    }


    @JsonProperty(JSON_PROPERTY_ZINSSALDO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinssaldo(BigDecimal zinssaldo) {
        this.zinssaldo = zinssaldo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TilgungsplanZeile tilgungsplanZeile = (TilgungsplanZeile) o;
        return Objects.equals(this.aktuellerZins, tilgungsplanZeile.aktuellerZins) &&
                Objects.equals(this.bewegung, tilgungsplanZeile.bewegung) &&
                Objects.equals(this.art, tilgungsplanZeile.art) &&
                Objects.equals(this.restkapital, tilgungsplanZeile.restkapital) &&
                Objects.equals(this.tilgung, tilgungsplanZeile.tilgung) &&
                Objects.equals(this.valuta, tilgungsplanZeile.valuta) &&
                Objects.equals(this.zins, tilgungsplanZeile.zins) &&
                Objects.equals(this.zinssaldo, tilgungsplanZeile.zinssaldo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(aktuellerZins, bewegung, art, restkapital, tilgung, valuta, zins, zinssaldo);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TilgungsplanZeile {\n");
        sb.append("    aktuellerZins: ").append(toIndentedString(aktuellerZins)).append("\n");
        sb.append("    bewegung: ").append(toIndentedString(bewegung)).append("\n");
        sb.append("    art: ").append(toIndentedString(art)).append("\n");
        sb.append("    restkapital: ").append(toIndentedString(restkapital)).append("\n");
        sb.append("    tilgung: ").append(toIndentedString(tilgung)).append("\n");
        sb.append("    valuta: ").append(toIndentedString(valuta)).append("\n");
        sb.append("    zins: ").append(toIndentedString(zins)).append("\n");
        sb.append("    zinssaldo: ").append(toIndentedString(zinssaldo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

