/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VerwaltungsdatenIn
 */
@JsonPropertyOrder({
        VerwaltungsdatenIn.JSON_PROPERTY_IBAN,
        VerwaltungsdatenIn.JSON_PROPERTY_BIC,
        VerwaltungsdatenIn.JSON_PROPERTY_KONTONUMMER,
        VerwaltungsdatenIn.JSON_PROPERTY_BETRIEBSSTELLE,
        VerwaltungsdatenIn.JSON_PROPERTY_KUNDENANSPRECHPARTNER,
        VerwaltungsdatenIn.JSON_PROPERTY_VERWALTUNGSDATEN_KONFIGURIERBAR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class VerwaltungsdatenIn {
    public static final String JSON_PROPERTY_IBAN = "iban";
    private String iban;

    public static final String JSON_PROPERTY_BIC = "bic";
    private String bic;

    public static final String JSON_PROPERTY_KONTONUMMER = "kontonummer";
    private String kontonummer;

    public static final String JSON_PROPERTY_BETRIEBSSTELLE = "betriebsstelle";
    private String betriebsstelle;

    public static final String JSON_PROPERTY_KUNDENANSPRECHPARTNER = "kundenansprechpartner";
    private String kundenansprechpartner;

    public static final String JSON_PROPERTY_VERWALTUNGSDATEN_KONFIGURIERBAR = "verwaltungsdatenKonfigurierbar";
    private List<@Valid VerwaltungsdatenwertKonfigurierbar> verwaltungsdatenKonfigurierbar;

    public VerwaltungsdatenIn() {
    }

    public VerwaltungsdatenIn iban(String iban) {

        this.iban = iban;
        return this;
    }

    /**
     * International Bank Account Number
     *
     * @return iban
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_IBAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getIban() {
        return iban;
    }


    @JsonProperty(JSON_PROPERTY_IBAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIban(String iban) {
        this.iban = iban;
    }

    public VerwaltungsdatenIn bic(String bic) {

        this.bic = bic;
        return this;
    }

    /**
     * Business Identifier Code
     *
     * @return bic
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_BIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getBic() {
        return bic;
    }


    @JsonProperty(JSON_PROPERTY_BIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBic(String bic) {
        this.bic = bic;
    }

    public VerwaltungsdatenIn kontonummer(String kontonummer) {

        this.kontonummer = kontonummer;
        return this;
    }

    /**
     * Kontonummer des Geschäfts
     *
     * @return kontonummer
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_KONTONUMMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKontonummer() {
        return kontonummer;
    }


    @JsonProperty(JSON_PROPERTY_KONTONUMMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKontonummer(String kontonummer) {
        this.kontonummer = kontonummer;
    }

    public VerwaltungsdatenIn betriebsstelle(String betriebsstelle) {

        this.betriebsstelle = betriebsstelle;
        return this;
    }

    /**
     * Betriebsstelle/Kundenverantwortliche Stelle oder die Abteilung des Beraters oder dergleichen.
     *
     * @return betriebsstelle
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_BETRIEBSSTELLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getBetriebsstelle() {
        return betriebsstelle;
    }


    @JsonProperty(JSON_PROPERTY_BETRIEBSSTELLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBetriebsstelle(String betriebsstelle) {
        this.betriebsstelle = betriebsstelle;
    }

    public VerwaltungsdatenIn kundenansprechpartner(String kundenansprechpartner) {

        this.kundenansprechpartner = kundenansprechpartner;
        return this;
    }

    /**
     * Get kundenansprechpartner
     *
     * @return kundenansprechpartner
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_KUNDENANSPRECHPARTNER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKundenansprechpartner() {
        return kundenansprechpartner;
    }


    @JsonProperty(JSON_PROPERTY_KUNDENANSPRECHPARTNER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKundenansprechpartner(String kundenansprechpartner) {
        this.kundenansprechpartner = kundenansprechpartner;
    }

    public VerwaltungsdatenIn verwaltungsdatenKonfigurierbar(List<@Valid VerwaltungsdatenwertKonfigurierbar> verwaltungsdatenKonfigurierbar) {

        this.verwaltungsdatenKonfigurierbar = verwaltungsdatenKonfigurierbar;
        return this;
    }

    public VerwaltungsdatenIn addVerwaltungsdatenKonfigurierbarItem(VerwaltungsdatenwertKonfigurierbar verwaltungsdatenKonfigurierbarItem) {
        if (this.verwaltungsdatenKonfigurierbar == null) {
            this.verwaltungsdatenKonfigurierbar = new ArrayList<>();
        }
        this.verwaltungsdatenKonfigurierbar.add(verwaltungsdatenKonfigurierbarItem);
        return this;
    }

    /**
     * Get verwaltungsdatenKonfigurierbar
     *
     * @return verwaltungsdatenKonfigurierbar
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_VERWALTUNGSDATEN_KONFIGURIERBAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid VerwaltungsdatenwertKonfigurierbar> getVerwaltungsdatenKonfigurierbar() {
        return verwaltungsdatenKonfigurierbar;
    }


    @JsonProperty(JSON_PROPERTY_VERWALTUNGSDATEN_KONFIGURIERBAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVerwaltungsdatenKonfigurierbar(List<@Valid VerwaltungsdatenwertKonfigurierbar> verwaltungsdatenKonfigurierbar) {
        this.verwaltungsdatenKonfigurierbar = verwaltungsdatenKonfigurierbar;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerwaltungsdatenIn verwaltungsdatenIn = (VerwaltungsdatenIn) o;
        return Objects.equals(this.iban, verwaltungsdatenIn.iban) &&
                Objects.equals(this.bic, verwaltungsdatenIn.bic) &&
                Objects.equals(this.kontonummer, verwaltungsdatenIn.kontonummer) &&
                Objects.equals(this.betriebsstelle, verwaltungsdatenIn.betriebsstelle) &&
                Objects.equals(this.kundenansprechpartner, verwaltungsdatenIn.kundenansprechpartner) &&
                Objects.equals(this.verwaltungsdatenKonfigurierbar, verwaltungsdatenIn.verwaltungsdatenKonfigurierbar);
    }

    @Override
    public int hashCode() {
        return Objects.hash(iban, bic, kontonummer, betriebsstelle, kundenansprechpartner, verwaltungsdatenKonfigurierbar);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VerwaltungsdatenIn {\n");
        sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
        sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
        sb.append("    kontonummer: ").append(toIndentedString(kontonummer)).append("\n");
        sb.append("    betriebsstelle: ").append(toIndentedString(betriebsstelle)).append("\n");
        sb.append("    kundenansprechpartner: ").append(toIndentedString(kundenansprechpartner)).append("\n");
        sb.append("    verwaltungsdatenKonfigurierbar: ").append(toIndentedString(verwaltungsdatenKonfigurierbar)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

