/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;
import java.util.Objects;

/**
 * VerwaltungsdatenwertKonfigurierbar
 */
@JsonPropertyOrder({
        VerwaltungsdatenwertKonfigurierbar.JSON_PROPERTY_SCHLUESSEL,
        VerwaltungsdatenwertKonfigurierbar.JSON_PROPERTY_CHECKBOX,
        VerwaltungsdatenwertKonfigurierbar.JSON_PROPERTY_TEXT,
        VerwaltungsdatenwertKonfigurierbar.JSON_PROPERTY_DATUM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class VerwaltungsdatenwertKonfigurierbar {
    public static final String JSON_PROPERTY_SCHLUESSEL = "schluessel";
    private String schluessel;

    public static final String JSON_PROPERTY_CHECKBOX = "checkbox";
    private Boolean checkbox;

    public static final String JSON_PROPERTY_TEXT = "text";
    private String text;

    public static final String JSON_PROPERTY_DATUM = "datum";
    private LocalDate datum;

    public VerwaltungsdatenwertKonfigurierbar() {
    }

    public VerwaltungsdatenwertKonfigurierbar schluessel(String schluessel) {

        this.schluessel = schluessel;
        return this;
    }

    /**
     * Der Schlüssel des konfigurierbaren Verwaltungssdatenwerts.
     *
     * @return schluessel
     */
    @jakarta.annotation.Nonnull
    @NotNull

    @JsonProperty(JSON_PROPERTY_SCHLUESSEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getSchluessel() {
        return schluessel;
    }


    @JsonProperty(JSON_PROPERTY_SCHLUESSEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSchluessel(String schluessel) {
        this.schluessel = schluessel;
    }

    public VerwaltungsdatenwertKonfigurierbar checkbox(Boolean checkbox) {

        this.checkbox = checkbox;
        return this;
    }

    /**
     * Der Wert bei Datentyp CHECKBOX
     *
     * @return checkbox
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_CHECKBOX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getCheckbox() {
        return checkbox;
    }


    @JsonProperty(JSON_PROPERTY_CHECKBOX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCheckbox(Boolean checkbox) {
        this.checkbox = checkbox;
    }

    public VerwaltungsdatenwertKonfigurierbar text(String text) {

        this.text = text;
        return this;
    }

    /**
     * Der Wert bei Datentyp TEXT
     *
     * @return text
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getText() {
        return text;
    }


    @JsonProperty(JSON_PROPERTY_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setText(String text) {
        this.text = text;
    }

    public VerwaltungsdatenwertKonfigurierbar datum(LocalDate datum) {

        this.datum = datum;
        return this;
    }

    /**
     * Der Wert bei Datentyp DATUM
     *
     * @return datum
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LocalDate getDatum() {
        return datum;
    }


    @JsonProperty(JSON_PROPERTY_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDatum(LocalDate datum) {
        this.datum = datum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerwaltungsdatenwertKonfigurierbar verwaltungsdatenwertKonfigurierbar = (VerwaltungsdatenwertKonfigurierbar) o;
        return Objects.equals(this.schluessel, verwaltungsdatenwertKonfigurierbar.schluessel) &&
                Objects.equals(this.checkbox, verwaltungsdatenwertKonfigurierbar.checkbox) &&
                Objects.equals(this.text, verwaltungsdatenwertKonfigurierbar.text) &&
                Objects.equals(this.datum, verwaltungsdatenwertKonfigurierbar.datum);
    }

    @Override
    public int hashCode() {
        return Objects.hash(schluessel, checkbox, text, datum);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VerwaltungsdatenwertKonfigurierbar {\n");
        sb.append("    schluessel: ").append(toIndentedString(schluessel)).append("\n");
        sb.append("    checkbox: ").append(toIndentedString(checkbox)).append("\n");
        sb.append("    text: ").append(toIndentedString(text)).append("\n");
        sb.append("    datum: ").append(toIndentedString(datum)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

