/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Wenn ein Zinstermin auf einen Bankarbeitstag verschoben wird, kann mit diesem Parameter festgelegt werden, ob nur der Zinszahlungstermin verschoben werden soll oder auch der Zinsberechnungstermin.
 */
public enum WirksamkeitVerschiebung {

    ADJUSTED("ADJUSTED"),

    UNADJUSTED("UNADJUSTED");

    private String value;

    WirksamkeitVerschiebung(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static WirksamkeitVerschiebung fromValue(String value) {
        for (WirksamkeitVerschiebung b : WirksamkeitVerschiebung.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

