/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Zinsen können entweder ab dem ersten Zinsperiodenende gezahlt werden (ZAHLEN) oder sie werden bis zur ersten Rate kumuliert und an diesem Termin bezahlt (KUMULIEREN).
 */
public enum ZinsBisTilgungsbeginn {

    ZAHLEN("ZAHLEN"),

    KUMULIEREN("KUMULIEREN");

    private String value;

    ZinsBisTilgungsbeginn(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static ZinsBisTilgungsbeginn fromValue(String value) {
        for (ZinsBisTilgungsbeginn b : ZinsBisTilgungsbeginn.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

