/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * Angabe der Zinszahlungszeitpunkte
 */
@JsonPropertyOrder({
        Zinszahlung.JSON_PROPERTY_VORFAELLIGE_ZINSTAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Zinszahlung {
    public static final String JSON_PROPERTY_VORFAELLIGE_ZINSTAGE = "vorfaelligeZinstage";
    private Integer vorfaelligeZinstage;

    public Zinszahlung() {
    }

    public Zinszahlung vorfaelligeZinstage(Integer vorfaelligeZinstage) {

        this.vorfaelligeZinstage = vorfaelligeZinstage;
        return this;
    }

    /**
     * Es besteht die Möglichkeit, dass Zinsen vorfällig gezahlt werden. Hierbei wird immer von einem Monat von 30 Tagen ausgegangen, unabhängig von der eingestellten Zinsusance. Zum Beispiel werden bei einem ersten Zinsperiodenende am 31.03. und bei 10 vorfälligen Zinstagen die Zinsen bereits am 20.03. fällig.
     *
     * @return vorfaelligeZinstage
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_VORFAELLIGE_ZINSTAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getVorfaelligeZinstage() {
        return vorfaelligeZinstage;
    }


    @JsonProperty(JSON_PROPERTY_VORFAELLIGE_ZINSTAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVorfaelligeZinstage(Integer vorfaelligeZinstage) {
        this.vorfaelligeZinstage = vorfaelligeZinstage;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Zinszahlung zinszahlung = (Zinszahlung) o;
        return Objects.equals(this.vorfaelligeZinstage, zinszahlung.vorfaelligeZinstage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(vorfaelligeZinstage);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Zinszahlung {\n");
        sb.append("    vorfaelligeZinstage: ").append(toIndentedString(vorfaelligeZinstage)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

