/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * Im Abgrenzungsplan werden Zinsen, Gebühren und Disagio am Monatsultimo abgegrenzt. Zusätzlich wird die monatliche mittlere Restschuld, das unverbrauchte Disagio und das Restkapital ausgewiesen.
 */
@JsonPropertyOrder({
        AbgrenzungZeile.JSON_PROPERTY_DISAGIO,
        AbgrenzungZeile.JSON_PROPERTY_DURCHSCHNITTLICHE_RESTSCHULD,
        AbgrenzungZeile.JSON_PROPERTY_GEBUEHR,
        AbgrenzungZeile.JSON_PROPERTY_ULTIMO,
        AbgrenzungZeile.JSON_PROPERTY_ZINS,
        AbgrenzungZeile.JSON_PROPERTY_ZINSSALDO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class AbgrenzungZeile {
    public static final String JSON_PROPERTY_DISAGIO = "disagio";
    private BigDecimal disagio;

    public static final String JSON_PROPERTY_DURCHSCHNITTLICHE_RESTSCHULD = "durchschnittlicheRestschuld";
    private BigDecimal durchschnittlicheRestschuld;

    public static final String JSON_PROPERTY_GEBUEHR = "gebuehr";
    private BigDecimal gebuehr;

    public static final String JSON_PROPERTY_ULTIMO = "ultimo";
    private LocalDate ultimo;

    public static final String JSON_PROPERTY_ZINS = "zins";
    private BigDecimal zins;

    public static final String JSON_PROPERTY_ZINSSALDO = "zinssaldo";
    private BigDecimal zinssaldo;

    public AbgrenzungZeile() {
    }

    public AbgrenzungZeile disagio(BigDecimal disagio) {

        this.disagio = disagio;
        return this;
    }

    /**
     * Der Anteil des Disagios, der bei nominalzinsproportionaler Abgrenzung des Disagios auf diesen Monat entfällt.
     *
     * @return disagio
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_DISAGIO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDisagio() {
        return disagio;
    }


    @JsonProperty(JSON_PROPERTY_DISAGIO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDisagio(BigDecimal disagio) {
        this.disagio = disagio;
    }

    public AbgrenzungZeile durchschnittlicheRestschuld(BigDecimal durchschnittlicheRestschuld) {

        this.durchschnittlicheRestschuld = durchschnittlicheRestschuld;
        return this;
    }

    /**
     * Die durchschnittliche nominale Restschuld dieses Monats.
     *
     * @return durchschnittlicheRestschuld
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_DURCHSCHNITTLICHE_RESTSCHULD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDurchschnittlicheRestschuld() {
        return durchschnittlicheRestschuld;
    }


    @JsonProperty(JSON_PROPERTY_DURCHSCHNITTLICHE_RESTSCHULD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDurchschnittlicheRestschuld(BigDecimal durchschnittlicheRestschuld) {
        this.durchschnittlicheRestschuld = durchschnittlicheRestschuld;
    }

    public AbgrenzungZeile gebuehr(BigDecimal gebuehr) {

        this.gebuehr = gebuehr;
        return this;
    }

    /**
     * Der Anteil der Gebühren, der in diesen Monat fällt.
     *
     * @return gebuehr
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_GEBUEHR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getGebuehr() {
        return gebuehr;
    }


    @JsonProperty(JSON_PROPERTY_GEBUEHR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGebuehr(BigDecimal gebuehr) {
        this.gebuehr = gebuehr;
    }

    public AbgrenzungZeile ultimo(LocalDate ultimo) {

        this.ultimo = ultimo;
        return this;
    }

    /**
     * Der Ultimo des Monats, in dem die Werte abgegrenzt werden.
     *
     * @return ultimo
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ULTIMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LocalDate getUltimo() {
        return ultimo;
    }


    @JsonProperty(JSON_PROPERTY_ULTIMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUltimo(LocalDate ultimo) {
        this.ultimo = ultimo;
    }

    public AbgrenzungZeile zins(BigDecimal zins) {

        this.zins = zins;
        return this;
    }

    /**
     * Der in diesem Monat abgegrenzte Zins.
     *
     * @return zins
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getZins() {
        return zins;
    }


    @JsonProperty(JSON_PROPERTY_ZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZins(BigDecimal zins) {
        this.zins = zins;
    }

    public AbgrenzungZeile zinssaldo(BigDecimal zinssaldo) {

        this.zinssaldo = zinssaldo;
        return this;
    }

    /**
     * Der in diesem Monat verbleibende Zinssaldo.
     *
     * @return zinssaldo
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSSALDO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getZinssaldo() {
        return zinssaldo;
    }


    @JsonProperty(JSON_PROPERTY_ZINSSALDO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinssaldo(BigDecimal zinssaldo) {
        this.zinssaldo = zinssaldo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AbgrenzungZeile abgrenzungZeile = (AbgrenzungZeile) o;
        return Objects.equals(this.disagio, abgrenzungZeile.disagio) &&
                Objects.equals(this.durchschnittlicheRestschuld, abgrenzungZeile.durchschnittlicheRestschuld) &&
                Objects.equals(this.gebuehr, abgrenzungZeile.gebuehr) &&
                Objects.equals(this.ultimo, abgrenzungZeile.ultimo) &&
                Objects.equals(this.zins, abgrenzungZeile.zins) &&
                Objects.equals(this.zinssaldo, abgrenzungZeile.zinssaldo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(disagio, durchschnittlicheRestschuld, gebuehr, ultimo, zins, zinssaldo);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AbgrenzungZeile {\n");
        sb.append("    disagio: ").append(toIndentedString(disagio)).append("\n");
        sb.append("    durchschnittlicheRestschuld: ").append(toIndentedString(durchschnittlicheRestschuld)).append("\n");
        sb.append("    gebuehr: ").append(toIndentedString(gebuehr)).append("\n");
        sb.append("    ultimo: ").append(toIndentedString(ultimo)).append("\n");
        sb.append("    zins: ").append(toIndentedString(zins)).append("\n");
        sb.append("    zinssaldo: ").append(toIndentedString(zinssaldo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

