/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Die Daten des Beraters
 */
@JsonPropertyOrder({
        Berater.JSON_PROPERTY_ANREDE,
        Berater.JSON_PROPERTY_NAME,
        Berater.JSON_PROPERTY_ADRESSE,
        Berater.JSON_PROPERTY_TELEFON,
        Berater.JSON_PROPERTY_FAX,
        Berater.JSON_PROPERTY_SACHBEARBEITERNUMMER,
        Berater.JSON_PROPERTY_EMAIL,
        Berater.JSON_PROPERTY_KUERZEL,
        Berater.JSON_PROPERTY_KOMMENTAR,
        Berater.JSON_PROPERTY_VERTRIEBSENDSTELLE,
        Berater.JSON_PROPERTY_GRUPPEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Berater {
    public static final String JSON_PROPERTY_ANREDE = "anrede";
    private String anrede;

    public static final String JSON_PROPERTY_NAME = "name";
    private Name name;

    public static final String JSON_PROPERTY_ADRESSE = "adresse";
    private Adresse adresse;

    public static final String JSON_PROPERTY_TELEFON = "telefon";
    private String telefon;

    public static final String JSON_PROPERTY_FAX = "fax";
    private String fax;

    public static final String JSON_PROPERTY_SACHBEARBEITERNUMMER = "sachbearbeiternummer";
    private String sachbearbeiternummer;

    public static final String JSON_PROPERTY_EMAIL = "email";
    private String email;

    public static final String JSON_PROPERTY_KUERZEL = "kuerzel";
    private String kuerzel;

    public static final String JSON_PROPERTY_KOMMENTAR = "kommentar";
    private String kommentar;

    public static final String JSON_PROPERTY_VERTRIEBSENDSTELLE = "vertriebsendstelle";
    private String vertriebsendstelle;

    public static final String JSON_PROPERTY_GRUPPEN = "gruppen";
    private List<String> gruppen;

    public Berater() {
    }

    public Berater anrede(String anrede) {

        this.anrede = anrede;
        return this;
    }

    /**
     * Die Anrede des Beraters
     *
     * @return anrede
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_ANREDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAnrede() {
        return anrede;
    }


    @JsonProperty(JSON_PROPERTY_ANREDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAnrede(String anrede) {
        this.anrede = anrede;
    }

    public Berater name(Name name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Name getName() {
        return name;
    }


    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(Name name) {
        this.name = name;
    }

    public Berater adresse(Adresse adresse) {

        this.adresse = adresse;
        return this;
    }

    /**
     * Get adresse
     *
     * @return adresse
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ADRESSE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Adresse getAdresse() {
        return adresse;
    }


    @JsonProperty(JSON_PROPERTY_ADRESSE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }

    public Berater telefon(String telefon) {

        this.telefon = telefon;
        return this;
    }

    /**
     * Die Telefonnummer des Beraters
     *
     * @return telefon
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_TELEFON)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTelefon() {
        return telefon;
    }


    @JsonProperty(JSON_PROPERTY_TELEFON)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

    public Berater fax(String fax) {

        this.fax = fax;
        return this;
    }

    /**
     * Fax des Beraters
     *
     * @return fax
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_FAX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getFax() {
        return fax;
    }


    @JsonProperty(JSON_PROPERTY_FAX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFax(String fax) {
        this.fax = fax;
    }

    public Berater sachbearbeiternummer(String sachbearbeiternummer) {

        this.sachbearbeiternummer = sachbearbeiternummer;
        return this;
    }

    /**
     * Die Sachbearbeiternummer
     *
     * @return sachbearbeiternummer
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_SACHBEARBEITERNUMMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSachbearbeiternummer() {
        return sachbearbeiternummer;
    }


    @JsonProperty(JSON_PROPERTY_SACHBEARBEITERNUMMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSachbearbeiternummer(String sachbearbeiternummer) {
        this.sachbearbeiternummer = sachbearbeiternummer;
    }

    public Berater email(String email) {

        this.email = email;
        return this;
    }

    /**
     * Die E-Mail des Beraters
     *
     * @return email
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_EMAIL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEmail() {
        return email;
    }


    @JsonProperty(JSON_PROPERTY_EMAIL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEmail(String email) {
        this.email = email;
    }

    public Berater kuerzel(String kuerzel) {

        this.kuerzel = kuerzel;
        return this;
    }

    /**
     * Das Kürzel des Beraters
     *
     * @return kuerzel
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_KUERZEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKuerzel() {
        return kuerzel;
    }


    @JsonProperty(JSON_PROPERTY_KUERZEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKuerzel(String kuerzel) {
        this.kuerzel = kuerzel;
    }

    public Berater kommentar(String kommentar) {

        this.kommentar = kommentar;
        return this;
    }

    /**
     * Der Kommentar, der auf dem Angebotsschreiben und dem Berechnungsprotokoll ausgewiesen wird.
     *
     * @return kommentar
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_KOMMENTAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKommentar() {
        return kommentar;
    }


    @JsonProperty(JSON_PROPERTY_KOMMENTAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKommentar(String kommentar) {
        this.kommentar = kommentar;
    }

    public Berater vertriebsendstelle(String vertriebsendstelle) {

        this.vertriebsendstelle = vertriebsendstelle;
        return this;
    }

    /**
     * Die Vertriebsendstelle des Beraters
     *
     * @return vertriebsendstelle
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_VERTRIEBSENDSTELLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getVertriebsendstelle() {
        return vertriebsendstelle;
    }


    @JsonProperty(JSON_PROPERTY_VERTRIEBSENDSTELLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVertriebsendstelle(String vertriebsendstelle) {
        this.vertriebsendstelle = vertriebsendstelle;
    }

    public Berater gruppen(List<String> gruppen) {

        this.gruppen = gruppen;
        return this;
    }

    public Berater addGruppenItem(String gruppenItem) {
        if (this.gruppen == null) {
            this.gruppen = new ArrayList<>();
        }
        this.gruppen.add(gruppenItem);
        return this;
    }

    /**
     * Liste aller Gruppen, in denen sich der Berater befindet.
     *
     * @return gruppen
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_GRUPPEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getGruppen() {
        return gruppen;
    }


    @JsonProperty(JSON_PROPERTY_GRUPPEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGruppen(List<String> gruppen) {
        this.gruppen = gruppen;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Berater berater = (Berater) o;
        return Objects.equals(this.anrede, berater.anrede) &&
                Objects.equals(this.name, berater.name) &&
                Objects.equals(this.adresse, berater.adresse) &&
                Objects.equals(this.telefon, berater.telefon) &&
                Objects.equals(this.fax, berater.fax) &&
                Objects.equals(this.sachbearbeiternummer, berater.sachbearbeiternummer) &&
                Objects.equals(this.email, berater.email) &&
                Objects.equals(this.kuerzel, berater.kuerzel) &&
                Objects.equals(this.kommentar, berater.kommentar) &&
                Objects.equals(this.vertriebsendstelle, berater.vertriebsendstelle) &&
                Objects.equals(this.gruppen, berater.gruppen);
    }

    @Override
    public int hashCode() {
        return Objects.hash(anrede, name, adresse, telefon, fax, sachbearbeiternummer, email, kuerzel, kommentar, vertriebsendstelle, gruppen);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Berater {\n");
        sb.append("    anrede: ").append(toIndentedString(anrede)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    adresse: ").append(toIndentedString(adresse)).append("\n");
        sb.append("    telefon: ").append(toIndentedString(telefon)).append("\n");
        sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
        sb.append("    sachbearbeiternummer: ").append(toIndentedString(sachbearbeiternummer)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    kuerzel: ").append(toIndentedString(kuerzel)).append("\n");
        sb.append("    kommentar: ").append(toIndentedString(kommentar)).append("\n");
        sb.append("    vertriebsendstelle: ").append(toIndentedString(vertriebsendstelle)).append("\n");
        sb.append("    gruppen: ").append(toIndentedString(gruppen)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

