/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Termine, die nicht auf Bankarbeitstage fallen, können auf den folgenden oder den vorherigen Bankarbeitstag verschoben werden (following/preceding). Mit der Einschränkung \&quot;modified\&quot; wird der Termin nur dann in diese Richtung verschoben, wenn er auch nach der Verschiebung im selben Monat liegt. Anderenfalls wird der Termin in die entgegengesetzte Richtung verschoben.
 */
public enum BusinessDayConvention {

    FIX("FIX"),

    FOLLOWING("FOLLOWING"),

    PRECEDING("PRECEDING"),

    MODIFIED_FOLLOWING("MODIFIED_FOLLOWING"),

    MODIFIED_PRECEDING("MODIFIED_PRECEDING"),

    MODIFIED_FOLLOWING_YEAR("MODIFIED_FOLLOWING_YEAR");

    private String value;

    BusinessDayConvention(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static BusinessDayConvention fromValue(String value) {
        for (BusinessDayConvention b : BusinessDayConvention.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

