/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.Objects;

/**
 * EffektivdatenRollover
 */
@JsonPropertyOrder({
        EffektivdatenRollover.JSON_PROPERTY_PANGVMODUS,
        EffektivdatenRollover.JSON_PROPERTY_ZINSUSANCE_EFFEKTIV
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class EffektivdatenRollover {
    public static final String JSON_PROPERTY_PANGVMODUS = "pangvmodus";
    private PAngVModus pangvmodus;

    public static final String JSON_PROPERTY_ZINSUSANCE_EFFEKTIV = "zinsusanceEffektiv";
    private Usance zinsusanceEffektiv;

    public EffektivdatenRollover() {
    }

    public EffektivdatenRollover pangvmodus(PAngVModus pangvmodus) {

        this.pangvmodus = pangvmodus;
        return this;
    }

    /**
     * Get pangvmodus
     *
     * @return pangvmodus
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_PANGVMODUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PAngVModus getPangvmodus() {
        return pangvmodus;
    }


    @JsonProperty(JSON_PROPERTY_PANGVMODUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPangvmodus(PAngVModus pangvmodus) {
        this.pangvmodus = pangvmodus;
    }

    public EffektivdatenRollover zinsusanceEffektiv(Usance zinsusanceEffektiv) {

        this.zinsusanceEffektiv = zinsusanceEffektiv;
        return this;
    }

    /**
     * Get zinsusanceEffektiv
     *
     * @return zinsusanceEffektiv
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSUSANCE_EFFEKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Usance getZinsusanceEffektiv() {
        return zinsusanceEffektiv;
    }


    @JsonProperty(JSON_PROPERTY_ZINSUSANCE_EFFEKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinsusanceEffektiv(Usance zinsusanceEffektiv) {
        this.zinsusanceEffektiv = zinsusanceEffektiv;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EffektivdatenRollover effektivdatenRollover = (EffektivdatenRollover) o;
        return Objects.equals(this.pangvmodus, effektivdatenRollover.pangvmodus) &&
                Objects.equals(this.zinsusanceEffektiv, effektivdatenRollover.zinsusanceEffektiv);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pangvmodus, zinsusanceEffektiv);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EffektivdatenRollover {\n");
        sb.append("    pangvmodus: ").append(toIndentedString(pangvmodus)).append("\n");
        sb.append("    zinsusanceEffektiv: ").append(toIndentedString(zinsusanceEffektiv)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

