/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Bei der Berechnung der prozentualen Marge kann die Marge entweder einmalig am Kalkulationsdatum (SOFORT) oder laufend zu jedem Zahlungsereignis (LAUFEND) entnommen werden.
 */
public enum Entnahmeart {

    SOFORT("SOFORT"),

    LAUFEND("LAUFEND");

    private String value;

    Entnahmeart(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static Entnahmeart fromValue(String value) {
        for (Entnahmeart b : Entnahmeart.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

