/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.Objects;

/**
 * Fehler, die während der Verarbeitung aufgetreten sind.
 */
@JsonPropertyOrder({
        Fehler.JSON_PROPERTY_FEHLERCODE,
        Fehler.JSON_PROPERTY_FELD,
        Fehler.JSON_PROPERTY_MELDUNG,
        Fehler.JSON_PROPERTY_HERKUNFT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Fehler {
    public static final String JSON_PROPERTY_FEHLERCODE = "fehlercode";
    private Integer fehlercode;

    public static final String JSON_PROPERTY_FELD = "feld";
    private String feld;

    public static final String JSON_PROPERTY_MELDUNG = "meldung";
    private String meldung;

    public static final String JSON_PROPERTY_HERKUNFT = "herkunft";
    private ReportingService herkunft;

    public Fehler() {
    }

    public Fehler fehlercode(Integer fehlercode) {

        this.fehlercode = fehlercode;
        return this;
    }

    /**
     * Optionaler numerischer Code für den Fehler.
     *
     * @return fehlercode
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_FEHLERCODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getFehlercode() {
        return fehlercode;
    }


    @JsonProperty(JSON_PROPERTY_FEHLERCODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFehlercode(Integer fehlercode) {
        this.fehlercode = fehlercode;
    }

    public Fehler feld(String feld) {

        this.feld = feld;
        return this;
    }

    /**
     * Feld im Datensatz, welches den Fehler verursacht hat.
     *
     * @return feld
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_FELD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getFeld() {
        return feld;
    }


    @JsonProperty(JSON_PROPERTY_FELD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFeld(String feld) {
        this.feld = feld;
    }

    public Fehler meldung(String meldung) {

        this.meldung = meldung;
        return this;
    }

    /**
     * Eine textuelle Beschreibung des Problems und Lösungshinweise.
     *
     * @return meldung
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_MELDUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMeldung() {
        return meldung;
    }


    @JsonProperty(JSON_PROPERTY_MELDUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMeldung(String meldung) {
        this.meldung = meldung;
    }

    public Fehler herkunft(ReportingService herkunft) {

        this.herkunft = herkunft;
        return this;
    }

    /**
     * Get herkunft
     *
     * @return herkunft
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_HERKUNFT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ReportingService getHerkunft() {
        return herkunft;
    }


    @JsonProperty(JSON_PROPERTY_HERKUNFT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHerkunft(ReportingService herkunft) {
        this.herkunft = herkunft;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Fehler fehler = (Fehler) o;
        return Objects.equals(this.fehlercode, fehler.fehlercode) &&
                Objects.equals(this.feld, fehler.feld) &&
                Objects.equals(this.meldung, fehler.meldung) &&
                Objects.equals(this.herkunft, fehler.herkunft);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fehlercode, feld, meldung, herkunft);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Fehler {\n");
        sb.append("    fehlercode: ").append(toIndentedString(fehlercode)).append("\n");
        sb.append("    feld: ").append(toIndentedString(feld)).append("\n");
        sb.append("    meldung: ").append(toIndentedString(meldung)).append("\n");
        sb.append("    herkunft: ").append(toIndentedString(herkunft)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

