/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * VOLL: Die erste Rate hat die gleiche Höhe wie die Folgeraten.ANTEILIG_ZINS: Der Tilgungsanteil der ersten Rate wird voll berechnet, die Zinsen nur anteilig.ANTEILIG_ZINS_TILGUNG: Sowohl Zins als auch Tilgung haben den Anteil am Zins bzw. Tilgung für eine volle erste Periode, den die Zeit zwischen Auszahlung und erstem Zinsberechnungstermin an einer gesamten Periodenlänge hat.
 */
public enum HoeheErsteRate {

    VOLL("VOLL"),

    ANTEILIG_ZINS("ANTEILIG_ZINS"),

    ANTEILIG_ZINS_TILGUNG("ANTEILIG_ZINS_TILGUNG");

    private String value;

    HoeheErsteRate(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static HoeheErsteRate fromValue(String value) {
        for (HoeheErsteRate b : HoeheErsteRate.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

