/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Institutskriterien
 */
@JsonPropertyOrder({
        Institutskriterien.JSON_PROPERTY_INSTITUTSKRITERIEN_AUSWAHL,
        Institutskriterien.JSON_PROPERTY_INSTITUTSKRITERIEN_WERT,
        Institutskriterien.JSON_PROPERTY_INSTITUTSKRITERIEN_DATUM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Institutskriterien {
    public static final String JSON_PROPERTY_INSTITUTSKRITERIEN_AUSWAHL = "institutskriterienAuswahl";
    private List<@Valid InstitutskriterienAuswahl> institutskriterienAuswahl;

    public static final String JSON_PROPERTY_INSTITUTSKRITERIEN_WERT = "institutskriterienWert";
    private List<@Valid InstitutskriterienWert> institutskriterienWert;

    public static final String JSON_PROPERTY_INSTITUTSKRITERIEN_DATUM = "institutskriterienDatum";
    private List<@Valid InstitutskriterienDatum> institutskriterienDatum;

    public Institutskriterien() {
    }

    public Institutskriterien institutskriterienAuswahl(List<@Valid InstitutskriterienAuswahl> institutskriterienAuswahl) {

        this.institutskriterienAuswahl = institutskriterienAuswahl;
        return this;
    }

    public Institutskriterien addInstitutskriterienAuswahlItem(InstitutskriterienAuswahl institutskriterienAuswahlItem) {
        if (this.institutskriterienAuswahl == null) {
            this.institutskriterienAuswahl = new ArrayList<>();
        }
        this.institutskriterienAuswahl.add(institutskriterienAuswahlItem);
        return this;
    }

    /**
     * Get institutskriterienAuswahl
     *
     * @return institutskriterienAuswahl
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_INSTITUTSKRITERIEN_AUSWAHL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid InstitutskriterienAuswahl> getInstitutskriterienAuswahl() {
        return institutskriterienAuswahl;
    }


    @JsonProperty(JSON_PROPERTY_INSTITUTSKRITERIEN_AUSWAHL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInstitutskriterienAuswahl(List<@Valid InstitutskriterienAuswahl> institutskriterienAuswahl) {
        this.institutskriterienAuswahl = institutskriterienAuswahl;
    }

    public Institutskriterien institutskriterienWert(List<@Valid InstitutskriterienWert> institutskriterienWert) {

        this.institutskriterienWert = institutskriterienWert;
        return this;
    }

    public Institutskriterien addInstitutskriterienWertItem(InstitutskriterienWert institutskriterienWertItem) {
        if (this.institutskriterienWert == null) {
            this.institutskriterienWert = new ArrayList<>();
        }
        this.institutskriterienWert.add(institutskriterienWertItem);
        return this;
    }

    /**
     * Get institutskriterienWert
     *
     * @return institutskriterienWert
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_INSTITUTSKRITERIEN_WERT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid InstitutskriterienWert> getInstitutskriterienWert() {
        return institutskriterienWert;
    }


    @JsonProperty(JSON_PROPERTY_INSTITUTSKRITERIEN_WERT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInstitutskriterienWert(List<@Valid InstitutskriterienWert> institutskriterienWert) {
        this.institutskriterienWert = institutskriterienWert;
    }

    public Institutskriterien institutskriterienDatum(List<@Valid InstitutskriterienDatum> institutskriterienDatum) {

        this.institutskriterienDatum = institutskriterienDatum;
        return this;
    }

    public Institutskriterien addInstitutskriterienDatumItem(InstitutskriterienDatum institutskriterienDatumItem) {
        if (this.institutskriterienDatum == null) {
            this.institutskriterienDatum = new ArrayList<>();
        }
        this.institutskriterienDatum.add(institutskriterienDatumItem);
        return this;
    }

    /**
     * Get institutskriterienDatum
     *
     * @return institutskriterienDatum
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_INSTITUTSKRITERIEN_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid InstitutskriterienDatum> getInstitutskriterienDatum() {
        return institutskriterienDatum;
    }


    @JsonProperty(JSON_PROPERTY_INSTITUTSKRITERIEN_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInstitutskriterienDatum(List<@Valid InstitutskriterienDatum> institutskriterienDatum) {
        this.institutskriterienDatum = institutskriterienDatum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Institutskriterien institutskriterien = (Institutskriterien) o;
        return Objects.equals(this.institutskriterienAuswahl, institutskriterien.institutskriterienAuswahl) &&
                Objects.equals(this.institutskriterienWert, institutskriterien.institutskriterienWert) &&
                Objects.equals(this.institutskriterienDatum, institutskriterien.institutskriterienDatum);
    }

    @Override
    public int hashCode() {
        return Objects.hash(institutskriterienAuswahl, institutskriterienWert, institutskriterienDatum);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Institutskriterien {\n");
        sb.append("    institutskriterienAuswahl: ").append(toIndentedString(institutskriterienAuswahl)).append("\n");
        sb.append("    institutskriterienWert: ").append(toIndentedString(institutskriterienWert)).append("\n");
        sb.append("    institutskriterienDatum: ").append(toIndentedString(institutskriterienDatum)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

