/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.Objects;

/**
 * Parameter, welche die Ausgestaltung des Kredits genauer beschreiben.
 */
@JsonPropertyOrder({
        KontofuehrungKredit.JSON_PROPERTY_ANNUITAETEN_METHODE,
        KontofuehrungKredit.JSON_PROPERTY_ANTEILIGE_LETZTE_RATE_BERECHNEN,
        KontofuehrungKredit.JSON_PROPERTY_AUSZAHLUNGSDATUM_ULTIMO,
        KontofuehrungKredit.JSON_PROPERTY_AUSZAHLUNGSTAG_VERZINST,
        KontofuehrungKredit.JSON_PROPERTY_PROLONGATION,
        KontofuehrungKredit.JSON_PROPERTY_RATENANGABE,
        KontofuehrungKredit.JSON_PROPERTY_RUECKZAHLUNGSTAG_VERZINST,
        KontofuehrungKredit.JSON_PROPERTY_RUNDUNG_BETRAEGE,
        KontofuehrungKredit.JSON_PROPERTY_RUNDUNG_NOMINALZINS,
        KontofuehrungKredit.JSON_PROPERTY_TILGUNGSANRECHNUNG,
        KontofuehrungKredit.JSON_PROPERTY_VERSCHIEBUNG,
        KontofuehrungKredit.JSON_PROPERTY_VERZINSUNGSVARIANTE,
        KontofuehrungKredit.JSON_PROPERTY_VOLLTILGUNG,
        KontofuehrungKredit.JSON_PROPERTY_ZINS_BIS_TILGUNGSBEGINN,
        KontofuehrungKredit.JSON_PROPERTY_ZINSBINDUNGSENDE_ULTIMO,
        KontofuehrungKredit.JSON_PROPERTY_ZINSUSANCE_NOMINAL,
        KontofuehrungKredit.JSON_PROPERTY_ZINSVERRECHNUNG,
        KontofuehrungKredit.JSON_PROPERTY_ZINSZAHLUNG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class KontofuehrungKredit {
    public static final String JSON_PROPERTY_ANNUITAETEN_METHODE = "annuitaetenMethode";
    private AnnuitaetenMethode annuitaetenMethode;

    public static final String JSON_PROPERTY_ANTEILIGE_LETZTE_RATE_BERECHNEN = "anteiligeLetzteRateBerechnen";
    private Boolean anteiligeLetzteRateBerechnen;

    public static final String JSON_PROPERTY_AUSZAHLUNGSDATUM_ULTIMO = "auszahlungsdatumUltimo";
    private VerwendungLetzterTagImFebruar auszahlungsdatumUltimo;

    public static final String JSON_PROPERTY_AUSZAHLUNGSTAG_VERZINST = "auszahlungstagVerzinst";
    private Boolean auszahlungstagVerzinst;

    public static final String JSON_PROPERTY_PROLONGATION = "prolongation";
    private ProlongationKredit prolongation;

    public static final String JSON_PROPERTY_RATENANGABE = "ratenangabe";
    private Ratenangabe ratenangabe;

    public static final String JSON_PROPERTY_RUECKZAHLUNGSTAG_VERZINST = "rueckzahlungstagVerzinst";
    private Boolean rueckzahlungstagVerzinst;

    public static final String JSON_PROPERTY_RUNDUNG_BETRAEGE = "rundungBetraege";
    private RundungsGenauigkeit rundungBetraege;

    public static final String JSON_PROPERTY_RUNDUNG_NOMINALZINS = "rundungNominalzins";
    private RundungsGenauigkeit rundungNominalzins;

    public static final String JSON_PROPERTY_TILGUNGSANRECHNUNG = "tilgungsanrechnung";
    private Tilgungsanrechnung tilgungsanrechnung;

    public static final String JSON_PROPERTY_VERSCHIEBUNG = "verschiebung";
    private Feiertagsverschiebung verschiebung;

    public static final String JSON_PROPERTY_VERZINSUNGSVARIANTE = "verzinsungsvariante";
    private Verzinsungsvariante verzinsungsvariante;

    public static final String JSON_PROPERTY_VOLLTILGUNG = "volltilgung";
    private Volltilgung volltilgung;

    public static final String JSON_PROPERTY_ZINS_BIS_TILGUNGSBEGINN = "zinsBisTilgungsbeginn";
    private ZinsBisTilgungsbeginn zinsBisTilgungsbeginn;

    public static final String JSON_PROPERTY_ZINSBINDUNGSENDE_ULTIMO = "zinsbindungsendeUltimo";
    private VerwendungLetzterTagImFebruar zinsbindungsendeUltimo;

    public static final String JSON_PROPERTY_ZINSUSANCE_NOMINAL = "zinsusanceNominal";
    private Usance zinsusanceNominal;

    public static final String JSON_PROPERTY_ZINSVERRECHNUNG = "zinsverrechnung";
    private Zinsverrechnung zinsverrechnung;

    public static final String JSON_PROPERTY_ZINSZAHLUNG = "zinszahlung";
    private Zinszahlung zinszahlung;

    public KontofuehrungKredit() {
    }

    public KontofuehrungKredit annuitaetenMethode(AnnuitaetenMethode annuitaetenMethode) {

        this.annuitaetenMethode = annuitaetenMethode;
        return this;
    }

    /**
     * Get annuitaetenMethode
     *
     * @return annuitaetenMethode
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ANNUITAETEN_METHODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AnnuitaetenMethode getAnnuitaetenMethode() {
        return annuitaetenMethode;
    }


    @JsonProperty(JSON_PROPERTY_ANNUITAETEN_METHODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAnnuitaetenMethode(AnnuitaetenMethode annuitaetenMethode) {
        this.annuitaetenMethode = annuitaetenMethode;
    }

    public KontofuehrungKredit anteiligeLetzteRateBerechnen(Boolean anteiligeLetzteRateBerechnen) {

        this.anteiligeLetzteRateBerechnen = anteiligeLetzteRateBerechnen;
        return this;
    }

    /**
     * Die letzte Rate im Annuitätendarlehen kann voll (false) oder zeitanteilig (true) ausgezahlt werden.
     *
     * @return anteiligeLetzteRateBerechnen
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_ANTEILIGE_LETZTE_RATE_BERECHNEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAnteiligeLetzteRateBerechnen() {
        return anteiligeLetzteRateBerechnen;
    }


    @JsonProperty(JSON_PROPERTY_ANTEILIGE_LETZTE_RATE_BERECHNEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAnteiligeLetzteRateBerechnen(Boolean anteiligeLetzteRateBerechnen) {
        this.anteiligeLetzteRateBerechnen = anteiligeLetzteRateBerechnen;
    }

    public KontofuehrungKredit auszahlungsdatumUltimo(VerwendungLetzterTagImFebruar auszahlungsdatumUltimo) {

        this.auszahlungsdatumUltimo = auszahlungsdatumUltimo;
        return this;
    }

    /**
     * Get auszahlungsdatumUltimo
     *
     * @return auszahlungsdatumUltimo
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_AUSZAHLUNGSDATUM_ULTIMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public VerwendungLetzterTagImFebruar getAuszahlungsdatumUltimo() {
        return auszahlungsdatumUltimo;
    }


    @JsonProperty(JSON_PROPERTY_AUSZAHLUNGSDATUM_ULTIMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAuszahlungsdatumUltimo(VerwendungLetzterTagImFebruar auszahlungsdatumUltimo) {
        this.auszahlungsdatumUltimo = auszahlungsdatumUltimo;
    }

    public KontofuehrungKredit auszahlungstagVerzinst(Boolean auszahlungstagVerzinst) {

        this.auszahlungstagVerzinst = auszahlungstagVerzinst;
        return this;
    }

    /**
     * Gibt an, ob der Tag der Auszahlung mitverzinst werden soll.
     *
     * @return auszahlungstagVerzinst
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_AUSZAHLUNGSTAG_VERZINST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAuszahlungstagVerzinst() {
        return auszahlungstagVerzinst;
    }


    @JsonProperty(JSON_PROPERTY_AUSZAHLUNGSTAG_VERZINST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAuszahlungstagVerzinst(Boolean auszahlungstagVerzinst) {
        this.auszahlungstagVerzinst = auszahlungstagVerzinst;
    }

    public KontofuehrungKredit prolongation(ProlongationKredit prolongation) {

        this.prolongation = prolongation;
        return this;
    }

    /**
     * Get prolongation
     *
     * @return prolongation
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_PROLONGATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ProlongationKredit getProlongation() {
        return prolongation;
    }


    @JsonProperty(JSON_PROPERTY_PROLONGATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProlongation(ProlongationKredit prolongation) {
        this.prolongation = prolongation;
    }

    public KontofuehrungKredit ratenangabe(Ratenangabe ratenangabe) {

        this.ratenangabe = ratenangabe;
        return this;
    }

    /**
     * Get ratenangabe
     *
     * @return ratenangabe
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RATENANGABE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Ratenangabe getRatenangabe() {
        return ratenangabe;
    }


    @JsonProperty(JSON_PROPERTY_RATENANGABE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRatenangabe(Ratenangabe ratenangabe) {
        this.ratenangabe = ratenangabe;
    }

    public KontofuehrungKredit rueckzahlungstagVerzinst(Boolean rueckzahlungstagVerzinst) {

        this.rueckzahlungstagVerzinst = rueckzahlungstagVerzinst;
        return this;
    }

    /**
     * Gibt an, ob der letzte Tag der Darlehenslaufzeit mitverzinst werden soll.
     *
     * @return rueckzahlungstagVerzinst
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_RUECKZAHLUNGSTAG_VERZINST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRueckzahlungstagVerzinst() {
        return rueckzahlungstagVerzinst;
    }


    @JsonProperty(JSON_PROPERTY_RUECKZAHLUNGSTAG_VERZINST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRueckzahlungstagVerzinst(Boolean rueckzahlungstagVerzinst) {
        this.rueckzahlungstagVerzinst = rueckzahlungstagVerzinst;
    }

    public KontofuehrungKredit rundungBetraege(RundungsGenauigkeit rundungBetraege) {

        this.rundungBetraege = rundungBetraege;
        return this;
    }

    /**
     * Get rundungBetraege
     *
     * @return rundungBetraege
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RUNDUNG_BETRAEGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public RundungsGenauigkeit getRundungBetraege() {
        return rundungBetraege;
    }


    @JsonProperty(JSON_PROPERTY_RUNDUNG_BETRAEGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRundungBetraege(RundungsGenauigkeit rundungBetraege) {
        this.rundungBetraege = rundungBetraege;
    }

    public KontofuehrungKredit rundungNominalzins(RundungsGenauigkeit rundungNominalzins) {

        this.rundungNominalzins = rundungNominalzins;
        return this;
    }

    /**
     * Get rundungNominalzins
     *
     * @return rundungNominalzins
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RUNDUNG_NOMINALZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public RundungsGenauigkeit getRundungNominalzins() {
        return rundungNominalzins;
    }


    @JsonProperty(JSON_PROPERTY_RUNDUNG_NOMINALZINS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRundungNominalzins(RundungsGenauigkeit rundungNominalzins) {
        this.rundungNominalzins = rundungNominalzins;
    }

    public KontofuehrungKredit tilgungsanrechnung(Tilgungsanrechnung tilgungsanrechnung) {

        this.tilgungsanrechnung = tilgungsanrechnung;
        return this;
    }

    /**
     * Get tilgungsanrechnung
     *
     * @return tilgungsanrechnung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_TILGUNGSANRECHNUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Tilgungsanrechnung getTilgungsanrechnung() {
        return tilgungsanrechnung;
    }


    @JsonProperty(JSON_PROPERTY_TILGUNGSANRECHNUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTilgungsanrechnung(Tilgungsanrechnung tilgungsanrechnung) {
        this.tilgungsanrechnung = tilgungsanrechnung;
    }

    public KontofuehrungKredit verschiebung(Feiertagsverschiebung verschiebung) {

        this.verschiebung = verschiebung;
        return this;
    }

    /**
     * Get verschiebung
     *
     * @return verschiebung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_VERSCHIEBUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Feiertagsverschiebung getVerschiebung() {
        return verschiebung;
    }


    @JsonProperty(JSON_PROPERTY_VERSCHIEBUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVerschiebung(Feiertagsverschiebung verschiebung) {
        this.verschiebung = verschiebung;
    }

    public KontofuehrungKredit verzinsungsvariante(Verzinsungsvariante verzinsungsvariante) {

        this.verzinsungsvariante = verzinsungsvariante;
        return this;
    }

    /**
     * Get verzinsungsvariante
     *
     * @return verzinsungsvariante
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_VERZINSUNGSVARIANTE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Verzinsungsvariante getVerzinsungsvariante() {
        return verzinsungsvariante;
    }


    @JsonProperty(JSON_PROPERTY_VERZINSUNGSVARIANTE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVerzinsungsvariante(Verzinsungsvariante verzinsungsvariante) {
        this.verzinsungsvariante = verzinsungsvariante;
    }

    public KontofuehrungKredit volltilgung(Volltilgung volltilgung) {

        this.volltilgung = volltilgung;
        return this;
    }

    /**
     * Get volltilgung
     *
     * @return volltilgung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_VOLLTILGUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Volltilgung getVolltilgung() {
        return volltilgung;
    }


    @JsonProperty(JSON_PROPERTY_VOLLTILGUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVolltilgung(Volltilgung volltilgung) {
        this.volltilgung = volltilgung;
    }

    public KontofuehrungKredit zinsBisTilgungsbeginn(ZinsBisTilgungsbeginn zinsBisTilgungsbeginn) {

        this.zinsBisTilgungsbeginn = zinsBisTilgungsbeginn;
        return this;
    }

    /**
     * Get zinsBisTilgungsbeginn
     *
     * @return zinsBisTilgungsbeginn
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINS_BIS_TILGUNGSBEGINN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ZinsBisTilgungsbeginn getZinsBisTilgungsbeginn() {
        return zinsBisTilgungsbeginn;
    }


    @JsonProperty(JSON_PROPERTY_ZINS_BIS_TILGUNGSBEGINN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinsBisTilgungsbeginn(ZinsBisTilgungsbeginn zinsBisTilgungsbeginn) {
        this.zinsBisTilgungsbeginn = zinsBisTilgungsbeginn;
    }

    public KontofuehrungKredit zinsbindungsendeUltimo(VerwendungLetzterTagImFebruar zinsbindungsendeUltimo) {

        this.zinsbindungsendeUltimo = zinsbindungsendeUltimo;
        return this;
    }

    /**
     * Get zinsbindungsendeUltimo
     *
     * @return zinsbindungsendeUltimo
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSBINDUNGSENDE_ULTIMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public VerwendungLetzterTagImFebruar getZinsbindungsendeUltimo() {
        return zinsbindungsendeUltimo;
    }


    @JsonProperty(JSON_PROPERTY_ZINSBINDUNGSENDE_ULTIMO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinsbindungsendeUltimo(VerwendungLetzterTagImFebruar zinsbindungsendeUltimo) {
        this.zinsbindungsendeUltimo = zinsbindungsendeUltimo;
    }

    public KontofuehrungKredit zinsusanceNominal(Usance zinsusanceNominal) {

        this.zinsusanceNominal = zinsusanceNominal;
        return this;
    }

    /**
     * Get zinsusanceNominal
     *
     * @return zinsusanceNominal
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSUSANCE_NOMINAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Usance getZinsusanceNominal() {
        return zinsusanceNominal;
    }


    @JsonProperty(JSON_PROPERTY_ZINSUSANCE_NOMINAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinsusanceNominal(Usance zinsusanceNominal) {
        this.zinsusanceNominal = zinsusanceNominal;
    }

    public KontofuehrungKredit zinsverrechnung(Zinsverrechnung zinsverrechnung) {

        this.zinsverrechnung = zinsverrechnung;
        return this;
    }

    /**
     * Get zinsverrechnung
     *
     * @return zinsverrechnung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSVERRECHNUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsverrechnung getZinsverrechnung() {
        return zinsverrechnung;
    }


    @JsonProperty(JSON_PROPERTY_ZINSVERRECHNUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinsverrechnung(Zinsverrechnung zinsverrechnung) {
        this.zinsverrechnung = zinsverrechnung;
    }

    public KontofuehrungKredit zinszahlung(Zinszahlung zinszahlung) {

        this.zinszahlung = zinszahlung;
        return this;
    }

    /**
     * Get zinszahlung
     *
     * @return zinszahlung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSZAHLUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinszahlung getZinszahlung() {
        return zinszahlung;
    }


    @JsonProperty(JSON_PROPERTY_ZINSZAHLUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinszahlung(Zinszahlung zinszahlung) {
        this.zinszahlung = zinszahlung;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        KontofuehrungKredit kontofuehrungKredit = (KontofuehrungKredit) o;
        return Objects.equals(this.annuitaetenMethode, kontofuehrungKredit.annuitaetenMethode) &&
                Objects.equals(this.anteiligeLetzteRateBerechnen, kontofuehrungKredit.anteiligeLetzteRateBerechnen) &&
                Objects.equals(this.auszahlungsdatumUltimo, kontofuehrungKredit.auszahlungsdatumUltimo) &&
                Objects.equals(this.auszahlungstagVerzinst, kontofuehrungKredit.auszahlungstagVerzinst) &&
                Objects.equals(this.prolongation, kontofuehrungKredit.prolongation) &&
                Objects.equals(this.ratenangabe, kontofuehrungKredit.ratenangabe) &&
                Objects.equals(this.rueckzahlungstagVerzinst, kontofuehrungKredit.rueckzahlungstagVerzinst) &&
                Objects.equals(this.rundungBetraege, kontofuehrungKredit.rundungBetraege) &&
                Objects.equals(this.rundungNominalzins, kontofuehrungKredit.rundungNominalzins) &&
                Objects.equals(this.tilgungsanrechnung, kontofuehrungKredit.tilgungsanrechnung) &&
                Objects.equals(this.verschiebung, kontofuehrungKredit.verschiebung) &&
                Objects.equals(this.verzinsungsvariante, kontofuehrungKredit.verzinsungsvariante) &&
                Objects.equals(this.volltilgung, kontofuehrungKredit.volltilgung) &&
                Objects.equals(this.zinsBisTilgungsbeginn, kontofuehrungKredit.zinsBisTilgungsbeginn) &&
                Objects.equals(this.zinsbindungsendeUltimo, kontofuehrungKredit.zinsbindungsendeUltimo) &&
                Objects.equals(this.zinsusanceNominal, kontofuehrungKredit.zinsusanceNominal) &&
                Objects.equals(this.zinsverrechnung, kontofuehrungKredit.zinsverrechnung) &&
                Objects.equals(this.zinszahlung, kontofuehrungKredit.zinszahlung);
    }

    @Override
    public int hashCode() {
        return Objects.hash(annuitaetenMethode, anteiligeLetzteRateBerechnen, auszahlungsdatumUltimo, auszahlungstagVerzinst, prolongation, ratenangabe, rueckzahlungstagVerzinst, rundungBetraege, rundungNominalzins, tilgungsanrechnung, verschiebung, verzinsungsvariante, volltilgung, zinsBisTilgungsbeginn, zinsbindungsendeUltimo, zinsusanceNominal, zinsverrechnung, zinszahlung);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class KontofuehrungKredit {\n");
        sb.append("    annuitaetenMethode: ").append(toIndentedString(annuitaetenMethode)).append("\n");
        sb.append("    anteiligeLetzteRateBerechnen: ").append(toIndentedString(anteiligeLetzteRateBerechnen)).append("\n");
        sb.append("    auszahlungsdatumUltimo: ").append(toIndentedString(auszahlungsdatumUltimo)).append("\n");
        sb.append("    auszahlungstagVerzinst: ").append(toIndentedString(auszahlungstagVerzinst)).append("\n");
        sb.append("    prolongation: ").append(toIndentedString(prolongation)).append("\n");
        sb.append("    ratenangabe: ").append(toIndentedString(ratenangabe)).append("\n");
        sb.append("    rueckzahlungstagVerzinst: ").append(toIndentedString(rueckzahlungstagVerzinst)).append("\n");
        sb.append("    rundungBetraege: ").append(toIndentedString(rundungBetraege)).append("\n");
        sb.append("    rundungNominalzins: ").append(toIndentedString(rundungNominalzins)).append("\n");
        sb.append("    tilgungsanrechnung: ").append(toIndentedString(tilgungsanrechnung)).append("\n");
        sb.append("    verschiebung: ").append(toIndentedString(verschiebung)).append("\n");
        sb.append("    verzinsungsvariante: ").append(toIndentedString(verzinsungsvariante)).append("\n");
        sb.append("    volltilgung: ").append(toIndentedString(volltilgung)).append("\n");
        sb.append("    zinsBisTilgungsbeginn: ").append(toIndentedString(zinsBisTilgungsbeginn)).append("\n");
        sb.append("    zinsbindungsendeUltimo: ").append(toIndentedString(zinsbindungsendeUltimo)).append("\n");
        sb.append("    zinsusanceNominal: ").append(toIndentedString(zinsusanceNominal)).append("\n");
        sb.append("    zinsverrechnung: ").append(toIndentedString(zinsverrechnung)).append("\n");
        sb.append("    zinszahlung: ").append(toIndentedString(zinszahlung)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

