/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * Die Laufzeit als Dauer bis Zinsbindungsende oder des Zinsbindungsende-Datums. Wenn das Feld gefüllt ist muss entweder die Dauer bis Zinsbindungsende oder das Datum des Zinsbindungsendes angegeben werden.
 */
@JsonPropertyOrder({
        LaufzeitInformation.JSON_PROPERTY_DATUM,
        LaufzeitInformation.JSON_PROPERTY_DAUER_IN_JAHREN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class LaufzeitInformation {
    public static final String JSON_PROPERTY_DATUM = "datum";
    private LocalDate datum;

    public static final String JSON_PROPERTY_DAUER_IN_JAHREN = "dauerInJahren";
    private BigDecimal dauerInJahren;

    public LaufzeitInformation() {
    }

    public LaufzeitInformation datum(LocalDate datum) {

        this.datum = datum;
        return this;
    }

    /**
     * Das Zinsbindungsende kann als String in dem Format YYYY-MM-DD angegeben werden.
     *
     * @return datum
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LocalDate getDatum() {
        return datum;
    }


    @JsonProperty(JSON_PROPERTY_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDatum(LocalDate datum) {
        this.datum = datum;
    }

    public LaufzeitInformation dauerInJahren(BigDecimal dauerInJahren) {

        this.dauerInJahren = dauerInJahren;
        return this;
    }

    /**
     * Die Dauer bis zum Zinsbindungsende kann als Laufzeit in Jahren angegeben werden.
     *
     * @return dauerInJahren
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_DAUER_IN_JAHREN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDauerInJahren() {
        return dauerInJahren;
    }


    @JsonProperty(JSON_PROPERTY_DAUER_IN_JAHREN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDauerInJahren(BigDecimal dauerInJahren) {
        this.dauerInJahren = dauerInJahren;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LaufzeitInformation laufzeitInformation = (LaufzeitInformation) o;
        return Objects.equals(this.datum, laufzeitInformation.datum) &&
                Objects.equals(this.dauerInJahren, laufzeitInformation.dauerInJahren);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datum, dauerInJahren);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LaufzeitInformation {\n");
        sb.append("    datum: ").append(toIndentedString(datum)).append("\n");
        sb.append("    dauerInJahren: ").append(toIndentedString(dauerInJahren)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

