/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.Objects;

/**
 * MarktdatenZinsstrukturen
 */
@JsonPropertyOrder({
        MarktdatenZinsstrukturen.JSON_PROPERTY_REFINANZIERUNG,
        MarktdatenZinsstrukturen.JSON_PROPERTY_REFINANZIERUNG_UNGEDECKT,
        MarktdatenZinsstrukturen.JSON_PROPERTY_SWAPKURVE,
        MarktdatenZinsstrukturen.JSON_PROPERTY_RISIKOLOSE_KURVE,
        MarktdatenZinsstrukturen.JSON_PROPERTY_GESCHAEFTSAENDERUNG,
        MarktdatenZinsstrukturen.JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class MarktdatenZinsstrukturen {
    public static final String JSON_PROPERTY_REFINANZIERUNG = "refinanzierung";
    private Zinsstruktur refinanzierung;

    public static final String JSON_PROPERTY_REFINANZIERUNG_UNGEDECKT = "refinanzierungUngedeckt";
    private Zinsstruktur refinanzierungUngedeckt;

    public static final String JSON_PROPERTY_SWAPKURVE = "swapkurve";
    private Zinsstruktur swapkurve;

    public static final String JSON_PROPERTY_RISIKOLOSE_KURVE = "risikoloseKurve";
    private Zinsstruktur risikoloseKurve;

    public static final String JSON_PROPERTY_GESCHAEFTSAENDERUNG = "geschaeftsaenderung";
    private Zinsstruktur geschaeftsaenderung;

    public static final String JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS = "zinsstrukturUhrzeitAuswahlModus";
    private ZinsstrukturUhrzeitAuswahlModus zinsstrukturUhrzeitAuswahlModus;

    public MarktdatenZinsstrukturen() {
    }

    public MarktdatenZinsstrukturen refinanzierung(Zinsstruktur refinanzierung) {

        this.refinanzierung = refinanzierung;
        return this;
    }

    /**
     * Get refinanzierung
     *
     * @return refinanzierung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_REFINANZIERUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsstruktur getRefinanzierung() {
        return refinanzierung;
    }


    @JsonProperty(JSON_PROPERTY_REFINANZIERUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRefinanzierung(Zinsstruktur refinanzierung) {
        this.refinanzierung = refinanzierung;
    }

    public MarktdatenZinsstrukturen refinanzierungUngedeckt(Zinsstruktur refinanzierungUngedeckt) {

        this.refinanzierungUngedeckt = refinanzierungUngedeckt;
        return this;
    }

    /**
     * Get refinanzierungUngedeckt
     *
     * @return refinanzierungUngedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_REFINANZIERUNG_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsstruktur getRefinanzierungUngedeckt() {
        return refinanzierungUngedeckt;
    }


    @JsonProperty(JSON_PROPERTY_REFINANZIERUNG_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRefinanzierungUngedeckt(Zinsstruktur refinanzierungUngedeckt) {
        this.refinanzierungUngedeckt = refinanzierungUngedeckt;
    }

    public MarktdatenZinsstrukturen swapkurve(Zinsstruktur swapkurve) {

        this.swapkurve = swapkurve;
        return this;
    }

    /**
     * Get swapkurve
     *
     * @return swapkurve
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SWAPKURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsstruktur getSwapkurve() {
        return swapkurve;
    }


    @JsonProperty(JSON_PROPERTY_SWAPKURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSwapkurve(Zinsstruktur swapkurve) {
        this.swapkurve = swapkurve;
    }

    public MarktdatenZinsstrukturen risikoloseKurve(Zinsstruktur risikoloseKurve) {

        this.risikoloseKurve = risikoloseKurve;
        return this;
    }

    /**
     * Get risikoloseKurve
     *
     * @return risikoloseKurve
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RISIKOLOSE_KURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsstruktur getRisikoloseKurve() {
        return risikoloseKurve;
    }


    @JsonProperty(JSON_PROPERTY_RISIKOLOSE_KURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRisikoloseKurve(Zinsstruktur risikoloseKurve) {
        this.risikoloseKurve = risikoloseKurve;
    }

    public MarktdatenZinsstrukturen geschaeftsaenderung(Zinsstruktur geschaeftsaenderung) {

        this.geschaeftsaenderung = geschaeftsaenderung;
        return this;
    }

    /**
     * Get geschaeftsaenderung
     *
     * @return geschaeftsaenderung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_GESCHAEFTSAENDERUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsstruktur getGeschaeftsaenderung() {
        return geschaeftsaenderung;
    }


    @JsonProperty(JSON_PROPERTY_GESCHAEFTSAENDERUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGeschaeftsaenderung(Zinsstruktur geschaeftsaenderung) {
        this.geschaeftsaenderung = geschaeftsaenderung;
    }

    public MarktdatenZinsstrukturen zinsstrukturUhrzeitAuswahlModus(ZinsstrukturUhrzeitAuswahlModus zinsstrukturUhrzeitAuswahlModus) {

        this.zinsstrukturUhrzeitAuswahlModus = zinsstrukturUhrzeitAuswahlModus;
        return this;
    }

    /**
     * Get zinsstrukturUhrzeitAuswahlModus
     *
     * @return zinsstrukturUhrzeitAuswahlModus
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ZinsstrukturUhrzeitAuswahlModus getZinsstrukturUhrzeitAuswahlModus() {
        return zinsstrukturUhrzeitAuswahlModus;
    }


    @JsonProperty(JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinsstrukturUhrzeitAuswahlModus(ZinsstrukturUhrzeitAuswahlModus zinsstrukturUhrzeitAuswahlModus) {
        this.zinsstrukturUhrzeitAuswahlModus = zinsstrukturUhrzeitAuswahlModus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MarktdatenZinsstrukturen marktdatenZinsstrukturen = (MarktdatenZinsstrukturen) o;
        return Objects.equals(this.refinanzierung, marktdatenZinsstrukturen.refinanzierung) &&
                Objects.equals(this.refinanzierungUngedeckt, marktdatenZinsstrukturen.refinanzierungUngedeckt) &&
                Objects.equals(this.swapkurve, marktdatenZinsstrukturen.swapkurve) &&
                Objects.equals(this.risikoloseKurve, marktdatenZinsstrukturen.risikoloseKurve) &&
                Objects.equals(this.geschaeftsaenderung, marktdatenZinsstrukturen.geschaeftsaenderung) &&
                Objects.equals(this.zinsstrukturUhrzeitAuswahlModus, marktdatenZinsstrukturen.zinsstrukturUhrzeitAuswahlModus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(refinanzierung, refinanzierungUngedeckt, swapkurve, risikoloseKurve, geschaeftsaenderung, zinsstrukturUhrzeitAuswahlModus);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MarktdatenZinsstrukturen {\n");
        sb.append("    refinanzierung: ").append(toIndentedString(refinanzierung)).append("\n");
        sb.append("    refinanzierungUngedeckt: ").append(toIndentedString(refinanzierungUngedeckt)).append("\n");
        sb.append("    swapkurve: ").append(toIndentedString(swapkurve)).append("\n");
        sb.append("    risikoloseKurve: ").append(toIndentedString(risikoloseKurve)).append("\n");
        sb.append("    geschaeftsaenderung: ").append(toIndentedString(geschaeftsaenderung)).append("\n");
        sb.append("    zinsstrukturUhrzeitAuswahlModus: ").append(toIndentedString(zinsstrukturUhrzeitAuswahlModus)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

