/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Die Zinsstrukturen, wenn sie mit FTPC berechnet wurden
 */
@JsonPropertyOrder({
        MarktdatenZinsstrukturenFtpc.JSON_PROPERTY_BASISKURVE,
        MarktdatenZinsstrukturenFtpc.JSON_PROPERTY_ANPASSUNG_BASISKURVE,
        MarktdatenZinsstrukturenFtpc.JSON_PROPERTY_PRICINGKRITERIEN,
        MarktdatenZinsstrukturenFtpc.JSON_PROPERTY_SPREADS,
        MarktdatenZinsstrukturenFtpc.JSON_PROPERTY_GESCHAEFTSAENDERUNG,
        MarktdatenZinsstrukturenFtpc.JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class MarktdatenZinsstrukturenFtpc {
    public static final String JSON_PROPERTY_BASISKURVE = "basiskurve";
    private Zinsstruktur basiskurve;

    public static final String JSON_PROPERTY_ANPASSUNG_BASISKURVE = "anpassungBasiskurve";
    private String anpassungBasiskurve;

    public static final String JSON_PROPERTY_PRICINGKRITERIEN = "pricingkriterien";
    private List<@Valid MarktdatenPricingkriterien> pricingkriterien;

    public static final String JSON_PROPERTY_SPREADS = "spreads";
    private List<@Valid MarktdatenSpreads> spreads;

    public static final String JSON_PROPERTY_GESCHAEFTSAENDERUNG = "geschaeftsaenderung";
    private Zinsstruktur geschaeftsaenderung;

    public static final String JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS = "zinsstrukturUhrzeitAuswahlModus";
    private ZinsstrukturUhrzeitAuswahlModus zinsstrukturUhrzeitAuswahlModus;

    public MarktdatenZinsstrukturenFtpc() {
    }

    public MarktdatenZinsstrukturenFtpc basiskurve(Zinsstruktur basiskurve) {

        this.basiskurve = basiskurve;
        return this;
    }

    /**
     * Get basiskurve
     *
     * @return basiskurve
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_BASISKURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsstruktur getBasiskurve() {
        return basiskurve;
    }


    @JsonProperty(JSON_PROPERTY_BASISKURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBasiskurve(Zinsstruktur basiskurve) {
        this.basiskurve = basiskurve;
    }

    public MarktdatenZinsstrukturenFtpc anpassungBasiskurve(String anpassungBasiskurve) {

        this.anpassungBasiskurve = anpassungBasiskurve;
        return this;
    }

    /**
     * Die manuelle Anpassung der Basiskurve
     *
     * @return anpassungBasiskurve
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_ANPASSUNG_BASISKURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAnpassungBasiskurve() {
        return anpassungBasiskurve;
    }


    @JsonProperty(JSON_PROPERTY_ANPASSUNG_BASISKURVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAnpassungBasiskurve(String anpassungBasiskurve) {
        this.anpassungBasiskurve = anpassungBasiskurve;
    }

    public MarktdatenZinsstrukturenFtpc pricingkriterien(List<@Valid MarktdatenPricingkriterien> pricingkriterien) {

        this.pricingkriterien = pricingkriterien;
        return this;
    }

    public MarktdatenZinsstrukturenFtpc addPricingkriterienItem(MarktdatenPricingkriterien pricingkriterienItem) {
        if (this.pricingkriterien == null) {
            this.pricingkriterien = new ArrayList<>();
        }
        this.pricingkriterien.add(pricingkriterienItem);
        return this;
    }

    /**
     * Get pricingkriterien
     *
     * @return pricingkriterien
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_PRICINGKRITERIEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid MarktdatenPricingkriterien> getPricingkriterien() {
        return pricingkriterien;
    }


    @JsonProperty(JSON_PROPERTY_PRICINGKRITERIEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPricingkriterien(List<@Valid MarktdatenPricingkriterien> pricingkriterien) {
        this.pricingkriterien = pricingkriterien;
    }

    public MarktdatenZinsstrukturenFtpc spreads(List<@Valid MarktdatenSpreads> spreads) {

        this.spreads = spreads;
        return this;
    }

    public MarktdatenZinsstrukturenFtpc addSpreadsItem(MarktdatenSpreads spreadsItem) {
        if (this.spreads == null) {
            this.spreads = new ArrayList<>();
        }
        this.spreads.add(spreadsItem);
        return this;
    }

    /**
     * Get spreads
     *
     * @return spreads
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SPREADS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid MarktdatenSpreads> getSpreads() {
        return spreads;
    }


    @JsonProperty(JSON_PROPERTY_SPREADS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSpreads(List<@Valid MarktdatenSpreads> spreads) {
        this.spreads = spreads;
    }

    public MarktdatenZinsstrukturenFtpc geschaeftsaenderung(Zinsstruktur geschaeftsaenderung) {

        this.geschaeftsaenderung = geschaeftsaenderung;
        return this;
    }

    /**
     * Get geschaeftsaenderung
     *
     * @return geschaeftsaenderung
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_GESCHAEFTSAENDERUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Zinsstruktur getGeschaeftsaenderung() {
        return geschaeftsaenderung;
    }


    @JsonProperty(JSON_PROPERTY_GESCHAEFTSAENDERUNG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGeschaeftsaenderung(Zinsstruktur geschaeftsaenderung) {
        this.geschaeftsaenderung = geschaeftsaenderung;
    }

    public MarktdatenZinsstrukturenFtpc zinsstrukturUhrzeitAuswahlModus(ZinsstrukturUhrzeitAuswahlModus zinsstrukturUhrzeitAuswahlModus) {

        this.zinsstrukturUhrzeitAuswahlModus = zinsstrukturUhrzeitAuswahlModus;
        return this;
    }

    /**
     * Get zinsstrukturUhrzeitAuswahlModus
     *
     * @return zinsstrukturUhrzeitAuswahlModus
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ZinsstrukturUhrzeitAuswahlModus getZinsstrukturUhrzeitAuswahlModus() {
        return zinsstrukturUhrzeitAuswahlModus;
    }


    @JsonProperty(JSON_PROPERTY_ZINSSTRUKTUR_UHRZEIT_AUSWAHL_MODUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinsstrukturUhrzeitAuswahlModus(ZinsstrukturUhrzeitAuswahlModus zinsstrukturUhrzeitAuswahlModus) {
        this.zinsstrukturUhrzeitAuswahlModus = zinsstrukturUhrzeitAuswahlModus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MarktdatenZinsstrukturenFtpc marktdatenZinsstrukturenFtpc = (MarktdatenZinsstrukturenFtpc) o;
        return Objects.equals(this.basiskurve, marktdatenZinsstrukturenFtpc.basiskurve) &&
                Objects.equals(this.anpassungBasiskurve, marktdatenZinsstrukturenFtpc.anpassungBasiskurve) &&
                Objects.equals(this.pricingkriterien, marktdatenZinsstrukturenFtpc.pricingkriterien) &&
                Objects.equals(this.spreads, marktdatenZinsstrukturenFtpc.spreads) &&
                Objects.equals(this.geschaeftsaenderung, marktdatenZinsstrukturenFtpc.geschaeftsaenderung) &&
                Objects.equals(this.zinsstrukturUhrzeitAuswahlModus, marktdatenZinsstrukturenFtpc.zinsstrukturUhrzeitAuswahlModus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(basiskurve, anpassungBasiskurve, pricingkriterien, spreads, geschaeftsaenderung, zinsstrukturUhrzeitAuswahlModus);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MarktdatenZinsstrukturenFtpc {\n");
        sb.append("    basiskurve: ").append(toIndentedString(basiskurve)).append("\n");
        sb.append("    anpassungBasiskurve: ").append(toIndentedString(anpassungBasiskurve)).append("\n");
        sb.append("    pricingkriterien: ").append(toIndentedString(pricingkriterien)).append("\n");
        sb.append("    spreads: ").append(toIndentedString(spreads)).append("\n");
        sb.append("    geschaeftsaenderung: ").append(toIndentedString(geschaeftsaenderung)).append("\n");
        sb.append("    zinsstrukturUhrzeitAuswahlModus: ").append(toIndentedString(zinsstrukturUhrzeitAuswahlModus)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

