/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * NeuerZinssatzTreppe
 */
@JsonPropertyOrder({
        NeuerZinssatzTreppe.JSON_PROPERTY_GUELTIG_AB,
        NeuerZinssatzTreppe.JSON_PROPERTY_ZINSSATZ
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class NeuerZinssatzTreppe {
    public static final String JSON_PROPERTY_GUELTIG_AB = "gueltigAb";
    private LocalDate gueltigAb;

    public static final String JSON_PROPERTY_ZINSSATZ = "zinssatz";
    private BigDecimal zinssatz;

    public NeuerZinssatzTreppe() {
    }

    public NeuerZinssatzTreppe gueltigAb(LocalDate gueltigAb) {

        this.gueltigAb = gueltigAb;
        return this;
    }

    /**
     * Das Datum, ab dem der neue Zinssatz gilt.
     *
     * @return gueltigAb
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_GUELTIG_AB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LocalDate getGueltigAb() {
        return gueltigAb;
    }


    @JsonProperty(JSON_PROPERTY_GUELTIG_AB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGueltigAb(LocalDate gueltigAb) {
        this.gueltigAb = gueltigAb;
    }

    public NeuerZinssatzTreppe zinssatz(BigDecimal zinssatz) {

        this.zinssatz = zinssatz;
        return this;
    }

    /**
     * Die Höhe des neuen Zinssatzes.
     *
     * @return zinssatz
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ZINSSATZ)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getZinssatz() {
        return zinssatz;
    }


    @JsonProperty(JSON_PROPERTY_ZINSSATZ)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZinssatz(BigDecimal zinssatz) {
        this.zinssatz = zinssatz;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NeuerZinssatzTreppe neuerZinssatzTreppe = (NeuerZinssatzTreppe) o;
        return Objects.equals(this.gueltigAb, neuerZinssatzTreppe.gueltigAb) &&
                Objects.equals(this.zinssatz, neuerZinssatzTreppe.zinssatz);
    }

    @Override
    public int hashCode() {
        return Objects.hash(gueltigAb, zinssatz);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NeuerZinssatzTreppe {\n");
        sb.append("    gueltigAb: ").append(toIndentedString(gueltigAb)).append("\n");
        sb.append("    zinssatz: ").append(toIndentedString(zinssatz)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

