/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Hier können vertraglich vereinbarte Ratenwechsel erfasst werden.
 */
@JsonPropertyOrder({
        Ratenwechsel.JSON_PROPERTY_RATENWECHSEL,
        Ratenwechsel.JSON_PROPERTY_AKTIV
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Ratenwechsel {
    public static final String JSON_PROPERTY_RATENWECHSEL = "ratenwechsel";
    private List<@Valid NeueRate> ratenwechsel;

    public static final String JSON_PROPERTY_AKTIV = "aktiv";
    private Boolean aktiv;

    public Ratenwechsel() {
    }

    public Ratenwechsel ratenwechsel(List<@Valid NeueRate> ratenwechsel) {

        this.ratenwechsel = ratenwechsel;
        return this;
    }

    public Ratenwechsel addRatenwechselItem(NeueRate ratenwechselItem) {
        if (this.ratenwechsel == null) {
            this.ratenwechsel = new ArrayList<>();
        }
        this.ratenwechsel.add(ratenwechselItem);
        return this;
    }

    /**
     * Tabelle der Ratenwechsel.
     *
     * @return ratenwechsel
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RATENWECHSEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<@Valid NeueRate> getRatenwechsel() {
        return ratenwechsel;
    }


    @JsonProperty(JSON_PROPERTY_RATENWECHSEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRatenwechsel(List<@Valid NeueRate> ratenwechsel) {
        this.ratenwechsel = ratenwechsel;
    }

    public Ratenwechsel aktiv(Boolean aktiv) {

        this.aktiv = aktiv;
        return this;
    }

    /**
     * Get aktiv
     *
     * @return aktiv
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_AKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAktiv() {
        return aktiv;
    }


    @JsonProperty(JSON_PROPERTY_AKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAktiv(Boolean aktiv) {
        this.aktiv = aktiv;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Ratenwechsel ratenwechsel = (Ratenwechsel) o;
        return Objects.equals(this.ratenwechsel, ratenwechsel.ratenwechsel) &&
                Objects.equals(this.aktiv, ratenwechsel.aktiv);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ratenwechsel, aktiv);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Ratenwechsel {\n");
        sb.append("    ratenwechsel: ").append(toIndentedString(ratenwechsel)).append("\n");
        sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

