/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Ratenangabe
 */
@JsonPropertyOrder({
        Ratenangabe.JSON_PROPERTY_ERSTE_RATE_AM,
        Ratenangabe.JSON_PROPERTY_HOEHE_ERSTE_RATE,
        Ratenangabe.JSON_PROPERTY_RHYTHMUS,
        Ratenangabe.JSON_PROPERTY_TAG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Ratenangabe {
    public static final String JSON_PROPERTY_ERSTE_RATE_AM = "ersteRateAm";
    private LocalDate ersteRateAm;

    public static final String JSON_PROPERTY_HOEHE_ERSTE_RATE = "hoeheErsteRate";
    private HoeheErsteRate hoeheErsteRate;

    public static final String JSON_PROPERTY_RHYTHMUS = "rhythmus";
    private PerAnnoAngabe rhythmus;

    public static final String JSON_PROPERTY_TAG = "tag";
    private UltimoTag tag;

    public Ratenangabe() {
    }

    public Ratenangabe ersteRateAm(LocalDate ersteRateAm) {

        this.ersteRateAm = ersteRateAm;
        return this;
    }

    /**
     * Der Tag an dem die erste Rate gezahlt wird. Damit kann eine verkürzte oder verlängerte erste Periode erreicht werden.
     *
     * @return ersteRateAm
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_ERSTE_RATE_AM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LocalDate getErsteRateAm() {
        return ersteRateAm;
    }


    @JsonProperty(JSON_PROPERTY_ERSTE_RATE_AM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setErsteRateAm(LocalDate ersteRateAm) {
        this.ersteRateAm = ersteRateAm;
    }

    public Ratenangabe hoeheErsteRate(HoeheErsteRate hoeheErsteRate) {

        this.hoeheErsteRate = hoeheErsteRate;
        return this;
    }

    /**
     * Get hoeheErsteRate
     *
     * @return hoeheErsteRate
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_HOEHE_ERSTE_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public HoeheErsteRate getHoeheErsteRate() {
        return hoeheErsteRate;
    }


    @JsonProperty(JSON_PROPERTY_HOEHE_ERSTE_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHoeheErsteRate(HoeheErsteRate hoeheErsteRate) {
        this.hoeheErsteRate = hoeheErsteRate;
    }

    public Ratenangabe rhythmus(PerAnnoAngabe rhythmus) {

        this.rhythmus = rhythmus;
        return this;
    }

    /**
     * Get rhythmus
     *
     * @return rhythmus
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_RHYTHMUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PerAnnoAngabe getRhythmus() {
        return rhythmus;
    }


    @JsonProperty(JSON_PROPERTY_RHYTHMUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRhythmus(PerAnnoAngabe rhythmus) {
        this.rhythmus = rhythmus;
    }

    public Ratenangabe tag(UltimoTag tag) {

        this.tag = tag;
        return this;
    }

    /**
     * Get tag
     *
     * @return tag
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_TAG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UltimoTag getTag() {
        return tag;
    }


    @JsonProperty(JSON_PROPERTY_TAG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTag(UltimoTag tag) {
        this.tag = tag;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Ratenangabe ratenangabe = (Ratenangabe) o;
        return Objects.equals(this.ersteRateAm, ratenangabe.ersteRateAm) &&
                Objects.equals(this.hoeheErsteRate, ratenangabe.hoeheErsteRate) &&
                Objects.equals(this.rhythmus, ratenangabe.rhythmus) &&
                Objects.equals(this.tag, ratenangabe.tag);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ersteRateAm, hoeheErsteRate, rhythmus, tag);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Ratenangabe {\n");
        sb.append("    ersteRateAm: ").append(toIndentedString(ersteRateAm)).append("\n");
        sb.append("    hoeheErsteRate: ").append(toIndentedString(hoeheErsteRate)).append("\n");
        sb.append("    rhythmus: ").append(toIndentedString(rhythmus)).append("\n");
        sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

