/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * TeildeckungsdatenRolloverSicht
 */
@JsonPropertyOrder({
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_MARGEDATEN_GEDECKT,
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_MARGEDATEN_UNGEDECKT,
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_SUMME_TILGUNGEN_GEDECKT,
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_SUMME_TILGUNGEN_UNGEDECKT,
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_SUMME_ZINSEN_GEDECKT,
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_SUMME_ZINSEN_UNGEDECKT,
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_SUMME_AUFSCHLAEGE_GEDECKT,
        TeildeckungsdatenRolloverSicht.JSON_PROPERTY_SUMME_AUFSCHLAEGE_UNGEDECKT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class TeildeckungsdatenRolloverSicht {
    public static final String JSON_PROPERTY_MARGEDATEN_GEDECKT = "margedatenGedeckt";
    private MargedatenRolloverSicht margedatenGedeckt;

    public static final String JSON_PROPERTY_MARGEDATEN_UNGEDECKT = "margedatenUngedeckt";
    private MargedatenRolloverSicht margedatenUngedeckt;

    public static final String JSON_PROPERTY_SUMME_TILGUNGEN_GEDECKT = "summeTilgungenGedeckt";
    private BigDecimal summeTilgungenGedeckt;

    public static final String JSON_PROPERTY_SUMME_TILGUNGEN_UNGEDECKT = "summeTilgungenUngedeckt";
    private BigDecimal summeTilgungenUngedeckt;

    public static final String JSON_PROPERTY_SUMME_ZINSEN_GEDECKT = "summeZinsenGedeckt";
    private BigDecimal summeZinsenGedeckt;

    public static final String JSON_PROPERTY_SUMME_ZINSEN_UNGEDECKT = "summeZinsenUngedeckt";
    private BigDecimal summeZinsenUngedeckt;

    public static final String JSON_PROPERTY_SUMME_AUFSCHLAEGE_GEDECKT = "summeAufschlaegeGedeckt";
    private BigDecimal summeAufschlaegeGedeckt;

    public static final String JSON_PROPERTY_SUMME_AUFSCHLAEGE_UNGEDECKT = "summeAufschlaegeUngedeckt";
    private BigDecimal summeAufschlaegeUngedeckt;

    public TeildeckungsdatenRolloverSicht() {
    }

    public TeildeckungsdatenRolloverSicht margedatenGedeckt(MargedatenRolloverSicht margedatenGedeckt) {

        this.margedatenGedeckt = margedatenGedeckt;
        return this;
    }

    /**
     * Get margedatenGedeckt
     *
     * @return margedatenGedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_MARGEDATEN_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public MargedatenRolloverSicht getMargedatenGedeckt() {
        return margedatenGedeckt;
    }


    @JsonProperty(JSON_PROPERTY_MARGEDATEN_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMargedatenGedeckt(MargedatenRolloverSicht margedatenGedeckt) {
        this.margedatenGedeckt = margedatenGedeckt;
    }

    public TeildeckungsdatenRolloverSicht margedatenUngedeckt(MargedatenRolloverSicht margedatenUngedeckt) {

        this.margedatenUngedeckt = margedatenUngedeckt;
        return this;
    }

    /**
     * Get margedatenUngedeckt
     *
     * @return margedatenUngedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_MARGEDATEN_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public MargedatenRolloverSicht getMargedatenUngedeckt() {
        return margedatenUngedeckt;
    }


    @JsonProperty(JSON_PROPERTY_MARGEDATEN_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMargedatenUngedeckt(MargedatenRolloverSicht margedatenUngedeckt) {
        this.margedatenUngedeckt = margedatenUngedeckt;
    }

    public TeildeckungsdatenRolloverSicht summeTilgungenGedeckt(BigDecimal summeTilgungenGedeckt) {

        this.summeTilgungenGedeckt = summeTilgungenGedeckt;
        return this;
    }

    /**
     * Die Summe der Tilgungen aus dem gedeckten Anteil des Kredits.
     *
     * @return summeTilgungenGedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SUMME_TILGUNGEN_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSummeTilgungenGedeckt() {
        return summeTilgungenGedeckt;
    }


    @JsonProperty(JSON_PROPERTY_SUMME_TILGUNGEN_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummeTilgungenGedeckt(BigDecimal summeTilgungenGedeckt) {
        this.summeTilgungenGedeckt = summeTilgungenGedeckt;
    }

    public TeildeckungsdatenRolloverSicht summeTilgungenUngedeckt(BigDecimal summeTilgungenUngedeckt) {

        this.summeTilgungenUngedeckt = summeTilgungenUngedeckt;
        return this;
    }

    /**
     * Die Summe der Tilgungen aus dem ungedeckten Anteil des Kredits.
     *
     * @return summeTilgungenUngedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SUMME_TILGUNGEN_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSummeTilgungenUngedeckt() {
        return summeTilgungenUngedeckt;
    }


    @JsonProperty(JSON_PROPERTY_SUMME_TILGUNGEN_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummeTilgungenUngedeckt(BigDecimal summeTilgungenUngedeckt) {
        this.summeTilgungenUngedeckt = summeTilgungenUngedeckt;
    }

    public TeildeckungsdatenRolloverSicht summeZinsenGedeckt(BigDecimal summeZinsenGedeckt) {

        this.summeZinsenGedeckt = summeZinsenGedeckt;
        return this;
    }

    /**
     * Die Summe der Zinsen aus dem gedeckten Anteil des Kredits.
     *
     * @return summeZinsenGedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SUMME_ZINSEN_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSummeZinsenGedeckt() {
        return summeZinsenGedeckt;
    }


    @JsonProperty(JSON_PROPERTY_SUMME_ZINSEN_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummeZinsenGedeckt(BigDecimal summeZinsenGedeckt) {
        this.summeZinsenGedeckt = summeZinsenGedeckt;
    }

    public TeildeckungsdatenRolloverSicht summeZinsenUngedeckt(BigDecimal summeZinsenUngedeckt) {

        this.summeZinsenUngedeckt = summeZinsenUngedeckt;
        return this;
    }

    /**
     * Die Summe der Zinsen aus dem ungedeckten Anteil des Kredits.
     *
     * @return summeZinsenUngedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SUMME_ZINSEN_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSummeZinsenUngedeckt() {
        return summeZinsenUngedeckt;
    }


    @JsonProperty(JSON_PROPERTY_SUMME_ZINSEN_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummeZinsenUngedeckt(BigDecimal summeZinsenUngedeckt) {
        this.summeZinsenUngedeckt = summeZinsenUngedeckt;
    }

    public TeildeckungsdatenRolloverSicht summeAufschlaegeGedeckt(BigDecimal summeAufschlaegeGedeckt) {

        this.summeAufschlaegeGedeckt = summeAufschlaegeGedeckt;
        return this;
    }

    /**
     * Summe aller Aufschläge für den gedeckten Teil.
     *
     * @return summeAufschlaegeGedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SUMME_AUFSCHLAEGE_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSummeAufschlaegeGedeckt() {
        return summeAufschlaegeGedeckt;
    }


    @JsonProperty(JSON_PROPERTY_SUMME_AUFSCHLAEGE_GEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummeAufschlaegeGedeckt(BigDecimal summeAufschlaegeGedeckt) {
        this.summeAufschlaegeGedeckt = summeAufschlaegeGedeckt;
    }

    public TeildeckungsdatenRolloverSicht summeAufschlaegeUngedeckt(BigDecimal summeAufschlaegeUngedeckt) {

        this.summeAufschlaegeUngedeckt = summeAufschlaegeUngedeckt;
        return this;
    }

    /**
     * Summe aller Aufschläge für den ungedeckten Teil.
     *
     * @return summeAufschlaegeUngedeckt
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_SUMME_AUFSCHLAEGE_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSummeAufschlaegeUngedeckt() {
        return summeAufschlaegeUngedeckt;
    }


    @JsonProperty(JSON_PROPERTY_SUMME_AUFSCHLAEGE_UNGEDECKT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummeAufschlaegeUngedeckt(BigDecimal summeAufschlaegeUngedeckt) {
        this.summeAufschlaegeUngedeckt = summeAufschlaegeUngedeckt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TeildeckungsdatenRolloverSicht teildeckungsdatenRolloverSicht = (TeildeckungsdatenRolloverSicht) o;
        return Objects.equals(this.margedatenGedeckt, teildeckungsdatenRolloverSicht.margedatenGedeckt) &&
                Objects.equals(this.margedatenUngedeckt, teildeckungsdatenRolloverSicht.margedatenUngedeckt) &&
                Objects.equals(this.summeTilgungenGedeckt, teildeckungsdatenRolloverSicht.summeTilgungenGedeckt) &&
                Objects.equals(this.summeTilgungenUngedeckt, teildeckungsdatenRolloverSicht.summeTilgungenUngedeckt) &&
                Objects.equals(this.summeZinsenGedeckt, teildeckungsdatenRolloverSicht.summeZinsenGedeckt) &&
                Objects.equals(this.summeZinsenUngedeckt, teildeckungsdatenRolloverSicht.summeZinsenUngedeckt) &&
                Objects.equals(this.summeAufschlaegeGedeckt, teildeckungsdatenRolloverSicht.summeAufschlaegeGedeckt) &&
                Objects.equals(this.summeAufschlaegeUngedeckt, teildeckungsdatenRolloverSicht.summeAufschlaegeUngedeckt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(margedatenGedeckt, margedatenUngedeckt, summeTilgungenGedeckt, summeTilgungenUngedeckt, summeZinsenGedeckt, summeZinsenUngedeckt, summeAufschlaegeGedeckt, summeAufschlaegeUngedeckt);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TeildeckungsdatenRolloverSicht {\n");
        sb.append("    margedatenGedeckt: ").append(toIndentedString(margedatenGedeckt)).append("\n");
        sb.append("    margedatenUngedeckt: ").append(toIndentedString(margedatenUngedeckt)).append("\n");
        sb.append("    summeTilgungenGedeckt: ").append(toIndentedString(summeTilgungenGedeckt)).append("\n");
        sb.append("    summeTilgungenUngedeckt: ").append(toIndentedString(summeTilgungenUngedeckt)).append("\n");
        sb.append("    summeZinsenGedeckt: ").append(toIndentedString(summeZinsenGedeckt)).append("\n");
        sb.append("    summeZinsenUngedeckt: ").append(toIndentedString(summeZinsenUngedeckt)).append("\n");
        sb.append("    summeAufschlaegeGedeckt: ").append(toIndentedString(summeAufschlaegeGedeckt)).append("\n");
        sb.append("    summeAufschlaegeUngedeckt: ").append(toIndentedString(summeAufschlaegeUngedeckt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

