/*
 * Geschäfte
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.msg4banking.processservice.application.model.transaction;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * Teilvalutierung
 */
@JsonPropertyOrder({
        Teilvalutierung.JSON_PROPERTY_DATUM,
        Teilvalutierung.JSON_PROPERTY_HOEHE_BETRAG,
        Teilvalutierung.JSON_PROPERTY_HOEHE_PROZENT,
        Teilvalutierung.JSON_PROPERTY_AKTIV
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-13T14:12:50.387795700+02:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Teilvalutierung {
    public static final String JSON_PROPERTY_DATUM = "datum";
    private LocalDate datum;

    public static final String JSON_PROPERTY_HOEHE_BETRAG = "hoeheBetrag";
    private BigDecimal hoeheBetrag;

    public static final String JSON_PROPERTY_HOEHE_PROZENT = "hoeheProzent";
    private BigDecimal hoeheProzent;

    public static final String JSON_PROPERTY_AKTIV = "aktiv";
    private Boolean aktiv;

    public Teilvalutierung() {
    }

    public Teilvalutierung datum(LocalDate datum) {

        this.datum = datum;
        return this;
    }

    /**
     * Das Datum der Teilvalutierung.
     *
     * @return datum
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LocalDate getDatum() {
        return datum;
    }


    @JsonProperty(JSON_PROPERTY_DATUM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDatum(LocalDate datum) {
        this.datum = datum;
    }

    public Teilvalutierung hoeheBetrag(BigDecimal hoeheBetrag) {

        this.hoeheBetrag = hoeheBetrag;
        return this;
    }

    /**
     * Die Höhe der Teilvalutierung als absoluter Betrag.
     *
     * @return hoeheBetrag
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_HOEHE_BETRAG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getHoeheBetrag() {
        return hoeheBetrag;
    }


    @JsonProperty(JSON_PROPERTY_HOEHE_BETRAG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHoeheBetrag(BigDecimal hoeheBetrag) {
        this.hoeheBetrag = hoeheBetrag;
    }

    public Teilvalutierung hoeheProzent(BigDecimal hoeheProzent) {

        this.hoeheProzent = hoeheProzent;
        return this;
    }

    /**
     * Die Höhe der Teilvalutierung als Prozentsatz des Nominalbetrags.
     *
     * @return hoeheProzent
     */
    @jakarta.annotation.Nullable
    @Valid

    @JsonProperty(JSON_PROPERTY_HOEHE_PROZENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getHoeheProzent() {
        return hoeheProzent;
    }


    @JsonProperty(JSON_PROPERTY_HOEHE_PROZENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHoeheProzent(BigDecimal hoeheProzent) {
        this.hoeheProzent = hoeheProzent;
    }

    public Teilvalutierung aktiv(Boolean aktiv) {

        this.aktiv = aktiv;
        return this;
    }

    /**
     * Get aktiv
     *
     * @return aktiv
     */
    @jakarta.annotation.Nullable

    @JsonProperty(JSON_PROPERTY_AKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAktiv() {
        return aktiv;
    }


    @JsonProperty(JSON_PROPERTY_AKTIV)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAktiv(Boolean aktiv) {
        this.aktiv = aktiv;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Teilvalutierung teilvalutierung = (Teilvalutierung) o;
        return Objects.equals(this.datum, teilvalutierung.datum) &&
                Objects.equals(this.hoeheBetrag, teilvalutierung.hoeheBetrag) &&
                Objects.equals(this.hoeheProzent, teilvalutierung.hoeheProzent) &&
                Objects.equals(this.aktiv, teilvalutierung.aktiv);
    }

    @Override
    public int hashCode() {
        return Objects.hash(datum, hoeheBetrag, hoeheProzent, aktiv);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Teilvalutierung {\n");
        sb.append("    datum: ").append(toIndentedString(datum)).append("\n");
        sb.append("    hoeheBetrag: ").append(toIndentedString(hoeheBetrag)).append("\n");
        sb.append("    hoeheProzent: ").append(toIndentedString(hoeheProzent)).append("\n");
        sb.append("    aktiv: ").append(toIndentedString(aktiv)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

